var GerlichUsageandCriticalThinking_survey = {
    type: jsPsychSurveyLikert,
    preamble: "<p style='font-size: 2.2vw;'><b> Please answer all of the questions on this page. </b></p>",
    questions:  [
        {prompt: "<b>1. How often do you use AI tools (e.g., virtual assistants, recommendation algorithms) to find information or solve problems?.</b>", name: 'GerlichUsageandCriticalThinking_Q1', labels: ["Never", "Rarely", "Sometimes", "Often", "Almost Always", "Always"], required: true},
        {prompt: "<b>2. To what extent do you rely on AI tools for decision-making?</b>", name: 'GerlichUsageandCriticalThinking_Q2', labels: ["Not at all", "Slightly", "Somewhat", "Moderately", "Almost always", "Completely"], required: true},
        {prompt: "<b>3. I find AI tools help me save time when searching for information.</b>", name: 'GerlichUsageandCriticalThinking_Q3', labels: ["Strongly Disagree", "Disagree", "Somewhat disagree", "Somewhat Agree", "Agree", "Strongly Agree"], required: true},
        {prompt: "<b>4. I trust the recommendations provided by AI tools.</b>", name: 'GerlichUsageandCriticalThinking_Q4', labels: ["Strongly Disagree", "Disagree", "Somewhat disagree", "Somewhat Agree", "Agree", "Strongly Agree"], required: true},
        {prompt: "<b>5. I often cross-check information provided by AI tools with other sources.</b>", name: 'GerlichUsageandCriticalThinking_Q5', labels: ["Strongly Disagree", "Disagree", "Somewhat disagree", "Somewaht Agree", "Agree", "Strongly Agree"], required: true},
        {prompt: "<b>6. How often do you critically evaluate the sources of information you encounter?</b>", name: 'GerlichUsageandCriticalThinking_Q6', labels: ["Never", "Rarely", "Sometimes", "Often", "Almost Always", "Always"], required: true}, 
        {prompt: "<b>7. How confident are you in your ability to discern fake news from legitimate news?</b>", name: 'GerlichUsageandCriticalThinkin_Q7', labels: ["Not confident at all", "Slightly confident", "Moderately confident", "Somewhat confident", "Mostly confident", "Very confident"], required: true},
        {prompt: "<b>8. When researching a topic, how often do you compare information from multiple sources?</b>", name: 'GerlichUsageandCriticalThinkin_Q8', labels: ["Never", "Rarely", "Sometimes", "Often", "Almost Always", "Always"], required: true},
        {prompt: "<b>9. How frequently do you reflect on the biases in your own thinking when making decisions?</b>", name: 'GerlichUsageandCriticalThinkin_Q9', labels: ["Never", "Rarely", "Sometimes", "Often", "Almost Always", "Always"], required: true},
        {prompt: "<b>10. How often do you question the motives behind the information shared by AI tools?</b>", name: 'GerlichUsageandCriticalThinkin_Q10', labels: ["Never", "Rarely", "Sometimes", "Often", "Almost Always", "Always"], required: true},
        {prompt: "<b>11. I analyse the credibility of the author when reading news or information provided by AI tools.</b>", name: 'GerlichUsageandCriticalThinkin_Q11', labels: ["Strongly Disagree", "Disagree", "Somewhat disagree", "Somewhat Agree", "Agree", "Strongly Agree"], required: true},
        {prompt: "<b>12. I compare multiple sources of information before forming an opinion based on AI recommendations.</b>", name: 'GerlichUsageandCriticalThinkin_Q12', labels: ["Strongly Disagree", "Disagree", "Somewhat disagree", "Somewhat Agree", "Agree", "Strongly Agree"], required: true},
        {prompt: "<b>13. I question the assumptions underlying the information provided by AI tools.</b>", name: 'GerlichUsageandCriticalThinkin_Q13', labels: ["Strongly Disagree", "Disagree", "Somewhat disagree", "Somewhat Agree", "Agree", "Strongly Agree"], required: true},
      ]
}