var assessment_stim_text = [
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Hubbardston, Massachusetts",
    "text_prompt": "NA",
    "text_stimuli (title)": "Private Entry, Full Kitchen, Close to Mt Wachuset",
    "text_stimuli": "Your home away from home is a spacious & newly renovated basement apartment /in-law suite (approx 1100 square feet), located below the main house & in walkable neighborhood. The unit has its own private entrance (bathroom, full kitchen, living room & bedroom with queen bed & extra tv). Hubbardston is a quaint little town with no stop-lights yet conveniently located to many beautiful hiking trails, fishing spots, lakes & only 15 minutes from Mt Wachusetts & 10 minutes from Rt 2 west.",
    "text_type": "Human",
    "text_word_count": 76,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "AL",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Overland Park, KS",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Overland Park, KS with the title Convenient Overland Park cottage on quiet street including pets being welcome",
    "text_stimuli (title)": "Convenient Overland Park Cottage on Quiet Street ñ Pets Welcome!",
    "text_stimuli": "Nestled on a serene, tree-lined street, this charming two-bedroom cottage offers a cozy retreat in Overland Park. Featuring a fully equipped kitchen, a fenced backyard for pets, and a comfortable living area, it's perfect for families or remote workers. Enjoy nearby parks, shops, and dining just minutes away. With free Wi-Fi, off-street parking, and pet-friendly amenities, this home ensures a relaxing stay for all\u2014whether you're visiting for business or leisure! Unwind on the cozy front porch with your morning coffee or evening tea.",
    "text_type": "AI",
    "text_word_count": 82,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Fort Collins, CO",
    "text_prompt": "NA",
    "text_stimuli (title)": "Colorado Modern Cabin",
    "text_stimuli": "This beautiful, modern cabin, is showered in sunlight. Just 2.5 miles from downtown, yet a stones throw from all the outdoor adventures in the foothills, Horsetooth Reservoir, Poudre River, mountain biking & hiking. With apple trees, berries & gardens, this quiet country setting is one of the best locations in town. Soak in the Colorado sunshine w/ the passive solar design. Relax in the evenings taking in the mountain sunsets while enjoying a fire pit on the back porch.",
    "text_type": "Human",
    "text_word_count": 77,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "AL",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Mesa, AZ",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Mesa, AZ with the title Near Lost Dutchman, Saguaro Lake & GoldfieldMine including its South-West theme",
    "text_stimuli (title)": "Near Lost Dutchman, Saguaro Lake & Goldfield Mine",
    "text_stimuli": "Experience a charming Southwest escape in Mesa, AZ, where rustic elegance meets modern amenities. This beautifully designed rental showcases warm desert hues, handcrafted wooden furnishings, and unique cactus-inspired accents. Unwind in the private courtyard with a cozy fire pit, or explore nearby attractions like Lost Dutchman State Park, Saguaro Lake, and Goldfield Ghost Town. With stunning mountain vistas and vibrant desert sunsets, this peaceful desert retreat offers charm and comfort for adventurers and history enthusiasts alike.",
    "text_type": "AI",
    "text_word_count": 76,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Spokane, Washington",
    "text_prompt": "NA",
    "text_stimuli (title)": "Funky D Barnery",
    "text_stimuli": "Come enjoy our beautiful private resort nestled next to our vineyard with breathtaking views of the sunset, sipping a glass of wine while taking a soak in the hot tub, or going full on Norwegian in the outdoor cedar sauna and plunge into the pool. Then come back inside, curl up by the wood stove and relax.\nWe have renovated this 1906 barn into a perfect guest suite including all the modern conveniences without losing the rustic elegance of the past. Welcome to the Funky D Ranch.",
    "text_type": "Human",
    "text_word_count": 87,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "AL",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Kansas City, Kansas",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Kansas City, Kansas with the title Enjoy Nature at Modern Farmhouse Close to City including it is a renovated 1933 bungalow",
    "text_stimuli (title)": "Enjoy Nature at Modern Farmhouse Close to City",
    "text_stimuli": "Experience the perfect blend of rustic charm and modern living in this beautifully renovated 1933 bungalow in Kansas City, Kansas. Surrounded by greenery, this cozy retreat offers an open-concept layout with a fully-equipped kitchen, original hardwood floors, and stylish vintage touches. Relax on the wraparound porch or gather around the outdoor firepit. Just minutes from downtown, this peaceful getaway provides a serene escape while keeping you close to the city's top attractions and amenities.",
    "text_type": "AI",
    "text_word_count": 74,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "El Paso, TX",
    "text_prompt": "NA",
    "text_stimuli (title)": "West side 5 bedroom home! Location! Location!!!",
    "text_stimuli": "This stylish place to stay is perfect for a family trip and group trips. This fully renovated home features 5 bedrooms and 3 full baths! While staying here you will be sleeping on 14 inch euro top mattresses in each bedroom. Spacious open concept designed home where you can create new memories with friends and family. 2 car port available for parking. Equipped with 2 refrigerated air units and washer and dryer! You will be minutes away from shopping and many restaurants. Minutes away from 1-10.",
    "text_type": "Human",
    "text_word_count": 86,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "AL/SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Nashville, TN",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Nashville, TN with the title Stylish Midcentury Gamehouse in East Nashville including its 60's ranch house aesthetic",
    "text_stimuli (title)": "Stylish Midcentury Gamehouse in East Nashville",
    "text_stimuli": "Experience retro vibes in this chic 1960s-inspired ranch home in East Nashville. Adorned with authentic midcentury furniture, vibrant colors, and vintage accents, it's a nostalgic getaway with modern flair. The game room boasts a pool table, retro arcade games, and a vinyl record collection for endless entertainment. Relax on the spacious patio with a firepit and grill. Conveniently located near trendy eateries and music spots, it's the ultimate mix of style, fun, and comfort.",
    "text_type": "AI",
    "text_word_count": 74,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Detroit, MI",
    "text_prompt": "NA",
    "text_stimuli (title)": "Minty Corktown Retreat with Garden",
    "text_stimuli": "Located in Detroit's Corktown historic district, a victorian bungalow home originally built in 1893 and renovated with a mid-century, eclectic contemporary interior. Enjoy a small outdoor garden for summer meals outside and across the street from a city park with a playground. Walking distance to Michigan Central and Michigan Ave. - Alba Coffee, Ima, Slow's BBQ, Motor City Wine, Mercury Bar, and more. One mile from downtown and riverfront.",
    "text_type": "Human",
    "text_word_count": 68,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "AL/SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Oklahoma City, OK",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Oklahoma City, OK with the title Cheerful 2-Bedroom Home in Paseo Arts District including being in the heart of the Paseo Arts district",
    "text_stimuli (title)": "Cheerful 2-Bedroom Home in Paseo Arts District",
    "text_stimuli": "Located in the lively Paseo Arts District of Oklahoma City, this delightful 2-bedroom home offers a welcoming escape. Surrounded by art galleries, boutique shops, and fantastic restaurants, it's perfect for exploring the area's creative vibe. The home features inviting decor, a fully equipped kitchen, and a cozy private patio for relaxing. Enjoy modern amenities, comfortable furnishings, and easy access to local attractions. With its prime location and warm atmosphere, this rental provides the ideal balance of comfort and culture in one of OKC's most vibrant neighborhoods.",
    "text_type": "AI",
    "text_word_count": 86,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Portland, OR",
    "text_prompt": "NA",
    "text_stimuli (title)": "Spacious, bright garden studio on Peninsula Park",
    "text_stimuli": "Explore the world-class restaurants, coffee shops and bars in the nearby Williams and Mississippi districts. Take a stroll around the award winning (and oldest) rose garden in the City of Roses across the street in Peninsula Park. At home, this second story studio has extra space in the meditation loft, a full kitchen, fast internet, and projector for streaming. Enjoy your private deck over the shared garden with hammock and H/C outdoor shower. Bus and train nearby with ample on-street parking.",
    "text_type": "Human",
    "text_word_count": 81,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "AL/SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Memphis, TN",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Memphis, TN with the title Whispering Oak Secret Hideaway including being built in 1908",
    "text_stimuli (title)": "Whispering Oak Secret Hideaway",
    "text_stimuli": "Discover timeless charm at this beautifully preserved 1908 craftsman in the heart of Memphis, TN. Whispering Oak Secret Hideaway is a peaceful retreat surrounded by majestic oak trees and vibrant gardens. Inside, original hardwood floors and stained glass windows evoke a bygone era, while modern comforts ensure a cozy stay. Relax in the private courtyard with a fire pit and twinkling lights. Just minutes from downtown, this hidden gem offers a perfect mix of history and Southern hospitality.",
    "text_type": "AI",
    "text_word_count": 78,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Laguna Beach, CA",
    "text_prompt": "NA",
    "text_stimuli (title)": "Inn Through the Orange Door-Laguna Village cottage",
    "text_stimuli": "Charming beach cottage ideally situated near Main Beach and downtown village. Master bedroom with ensuite bath and two guest bedrooms with Jack and Jill bath. Lovely front and side yards with BBQ and outside chaise area complemented by an outdoor shower room with Japanese soaking tub. Modern kitchen with all new appliances, garage has new washer / dryer, storage and bikes for exploring north and south Laguna. Fabulous location and a true walker's paradise!",
    "text_type": "Human",
    "text_word_count": 73,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Riverside, CA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Riverside, CA with the title eclectic studio | private courtyard including its private lit courtyard",
    "text_stimuli (title)": "Eclectic Studio | Private Courtyard",
    "text_stimuli": "Nestled in the heart of Riverside, this vibrant studio offers a fusion of vintage charm and modern comforts. Inside, enjoy bold decor, artistic accents, and a cozy kitchenette. Step outside to your private, illuminated courtyard, adorned with string lights, lush greenery, and a bistro table ñ perfect for evening relaxation or intimate dining. Conveniently located near downtown attractions, trendy cafes, art galleries, local markets, and historic landmarks, this retreat combines serenity with access to Riverside's lively culture.",
    "text_type": "AI",
    "text_word_count": 70,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Corpus Christi, TX",
    "text_prompt": "NA",
    "text_stimuli (title)": "Newly Renovated Bay Area Home",
    "text_stimuli": "Relax with the whole family at our newly renovated home. We are just a few blocks from the downtown life and many attractions that Corpus Christi has to offer. Cole park and the American Bank Center are minutes away as well as the downtown sea wall and area beach. If you are looking for beach access you are about 5 min away from McGee beach and 20 min to North Padre Island.",
    "text_type": "Human",
    "text_word_count": 72,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Lexington, KY",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Lexington, KY with the title The Rosewood Cottage of Lexington I Elegant & Cozy including its backyard fire pit",
    "text_stimuli (title)": "The Rosewood Cottage of Lexington | Elegant & Cozy",
    "text_stimuli": "Nestled in a quiet Lexington neighborhood, The Rosewood Cottage blends Southern charm with modern elegance. This boutique rental boasts a chic interior with a fully equipped kitchen, plush bedding, and vintage-inspired decor. The lush backyard features a cozy fire pit, perfect for roasting marshmallows under string lights and the stars. Just minutes from horse farms and downtown Lexington's vibrant attractions, this peaceful retreat invites guests to relax in style and explore Kentucky's beautiful Bluegrass region.",
    "text_type": "AI",
    "text_word_count": 72,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Henderson, NV",
    "text_prompt": "NA",
    "text_stimuli (title)": "Cozy Getaway w/ King Bed, BBQ & Spacious Backyard",
    "text_stimuli": "Welcome to your stylish home away from home! This beautifully remodeled 3-bedroom, 2-bathroom gem perfectly blends industrial edge with bohemian charm, offering a unique and comfortable stay just minutes from Henderson's top attractions like Lake Mead National Recreation Area, Water Street Entertainment District, Hoover Dam and Boulder City. Minutes from the freeway to take you anywhere Las Vegas has to offer.",
    "text_type": "Human",
    "text_word_count": 61,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Stockton, CA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Stockton, CA with the title Cozy Brick-house With Spacious Backyard including its lot size of 13,000 square feet.",
    "text_stimuli (title)": "Cozy Brick-house With Spacious Backyard",
    "text_stimuli": "Nestled in a serene Stockton neighborhood, this charming brick house offers the perfect retreat. Set on a sprawling 13,000-square-foot lot, it boasts a lush, spacious backyard ideal for outdoor activities, barbecues, or peaceful relaxation. Inside, enjoy modern amenities, cozy furnishings, and a warm, inviting ambiance. The home features three bedrooms, a well-equipped kitchen, and a cozy living area with a fireplace. Conveniently located near local attractions, it's perfect for families or couples seeking tranquility.",
    "text_type": "AI",
    "text_word_count": 74,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Gilbert, AZ",
    "text_prompt": "NA",
    "text_stimuli (title)": "Val vista Gilbert, beautiful modern home",
    "text_stimuli": "Unwind at our Modern Boho Gilbert Oasis in the beautiful Val Vista neighborhood. Enjoy the peaceful neighborhood with a relaxing backyard; including a sparkling pool, outdoor patio and pool lounge area. Enjoy some fresh oranges or grapefruits and play some outdoor games with the family. Minutes from downtown Gilbert where you're surrounded by fun shopping, great restaurants, much more! Golfing and Hiking in the near vicinity as well! Sought after location - central to most everything.",
    "text_type": "Human",
    "text_word_count": 75,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Glendale, AZ",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Glendale, AZ with the title Hot Tub | Heated Pool | Wood Sauna | Pizza oven including its pizza oven",
    "text_stimuli (title)": "Hot Tub | Heated Pool | Wood Sauna | Pizza Oven",
    "text_stimuli": "Escape to this luxurious vacation rental in Glendale, AZ, where relaxation and fun meet. Unwind in the heated pool, indulge in a soothing wood sauna, or melt away stress in the hot tub. For pizza lovers, a fully functional wood-fired pizza oven awaits, perfect for crafting delicious pies under the Arizona stars. With modern amenities, an outdoor grill, and a cozy, inviting atmosphere, this retreat is the ultimate getaway for relaxation, culinary delight, and unforgettable memories.",
    "text_type": "AI",
    "text_word_count": 71,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Reno, NV",
    "text_prompt": "NA",
    "text_stimuli (title)": "The Guesthouse",
    "text_stimuli": "The Guesthouse is unique in design and architecture. Similar vibe to a tiny home, it is packed with comfort and a little touch of 1930's elegance. From the bedroom there is a small balcony where you can sit in a rocking chair and enjoy the morning with a cup of coffee. Tucked below, there are two hammock chairs where you can listen to the soothing melody of a seasonal creek that gently flows nearby. In the evening, head to the front deck to catch the sun setting behind the mountains.",
    "text_type": "Human",
    "text_word_count": 90,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Winston-Salem, NC",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Winston-Salem, NC with the title Brand New Ardmore Townhome including it is a newly built summer home",
    "text_stimuli (title)": "Brand New Ardmore Townhome",
    "text_stimuli": "Nestled in the charming Ardmore neighborhood, this newly built summer home offers modern comfort with a touch of Southern hospitality. The spacious, light-filled townhome features three cozy bedrooms, a fully equipped kitchen, and an open-concept living area perfect for relaxing or entertaining. Enjoy the private backyard, perfect for al fresco dining. Located just minutes from downtown Winston-Salem, guests can easily explore local attractions, restaurants, and outdoor parks for a truly memorable stay.",
    "text_type": "AI",
    "text_word_count": 72,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Chesapeake, VA",
    "text_prompt": "NA",
    "text_stimuli (title)": "King Guest Suite - A Family Vacation Rental",
    "text_stimuli": "Come enjoy a great stay in this beautiful private In-law suite, located in the heart of Chesapeake where you can get lost in nature, peruse the fare at a farmer's market, or picnic on the water's edge with your family. Just within 15 to 30 minutes from surrounding Naval bases, Virginia Beach Oceanfront and Downtown Norfolk. All you have to do us gas-up and unplug. We'll take it from there. Reserve your stay today and let your moments begin!",
    "text_type": "Human",
    "text_word_count": 79,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Norfolk, VA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Norfolk, VA with the title Positano Villa including its private beach",
    "text_stimuli (title)": "Positano Villa",
    "text_stimuli": "Positano Villa in Norfolk, VA, offers a luxurious escape with breathtaking views of the Chesapeake Bay. This Mediterranean-inspired villa features a spacious open-plan living area, four elegantly appointed bedrooms, and expansive terraces. Guests enjoy exclusive access to a pristine private beach, perfect for sunbathing, water activities, or relaxing walks. Surrounded by lush gardens and vibrant colors, Positano Villa blends relaxation and adventure, providing an unforgettable retreat with modern amenities, coastal charm, and incredible sunset views each evening.",
    "text_type": "AI",
    "text_word_count": 77,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Lansing, MI",
    "text_prompt": "NA",
    "text_stimuli (title)": "Sunsets on the Grand",
    "text_stimuli": "Mid-Modern stylish condo with views of Grand River! Minutes from shopping, restaurants, and downtown Lansing. Take a walk or bike along the River trail, or head to beautiful Frances Park and enjoy the peaceful views of the rose garden. Just a stones throw away from MSU & Lansing Row Clubs and the public boat launch. Only a 10-minute drive to Michigan State University! Extra amenities provided so you have everything you need for a comfy stay while visiting us here in the capital city of Michigan.",
    "text_type": "Human",
    "text_word_count": 85,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Huntsville, AL",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Huntsville, AL with the title \" Magical Mountain Retreat with Vintage Charm\" including a detail about the location.",
    "text_stimuli (title)": "Magical Mountain Retreat with Vintage Charm",
    "text_stimuli": "Nestled in Monte Sano Mountain's heritage district, this captivating 1940s cottage commands breathtaking valley vistas mere minutes from Huntsville's center. The 750-square-foot sanctuary rests adjacent to Monte Sano State Park's trail network, showcasing authentic stone masonry, expansive windows, and an intimate viewing deck ideal for celestial observation. Situated within the historic resort neighborhood, this thoughtfully preserved haven blends mountain tranquility with urban accessibility, featuring original hardwood floors and hand-forged ironwork that echoes its timeless mountain charm.",
    "text_type": "AI",
    "text_word_count": 76,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 2.3,
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Salt Lake City, UT",
    "text_prompt": "NA",
    "text_stimuli (title)": "Adorable Pink Cottage, Private Hot Tub, Downtown!",
    "text_stimuli": "Our hot tubs are serviced daily making sure the chlorine levels are clean, healthy, and safe per CDC guidelines. You'll have exclusive access to the hot tub for your use only. Conveniently located a block from Trax taking you directly to the Salt Palace Convention Center, Vivint, City Creek with connections to the Airport. This quaint Victorian-style duplex is located on a quiet dead-end street. No one is above or below you allowing for a quieter stay without hearing footsteps above you.",
    "text_type": "Human",
    "text_word_count": 82,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Peoria, IL",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Peoria, IL with the title \" BlackbirdÖOn the Drive \" including a detail about the amenities.",
    "text_stimuli (title)": "Blackbird...On the Drive",
    "text_stimuli": "Positioned along prestigious Grand View Drive in Peoria Heights, this elegant 1,200-square-foot guest retreat commands stunning Illinois River Valley vistas. The meticulously updated interior showcases a chef's kitchen with premium Viking appliances, luxurious heated marble bathroom flooring, and a secluded deck for evening sunsets. Modern home automation manages ambiance and comfort, complemented by a bespoke wine bar and cozy hearth, while custom-built walnut shelving and handcrafted light fixtures enhance its refined character and timeless design.",
    "text_type": "AI",
    "text_word_count": 75,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0.1,
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Knoxville, TN",
    "text_prompt": "NA",
    "text_stimuli (title)": "Mims Cottage",
    "text_stimuli": "This cottage is located in the renovated basement of an owner-occupied home, and has a private entrance. Nestled in a small neighborhood near Holston Hills, this cottage is a dream! Enjoy a pour over on the patio before heading downtown to experience the award winning farmer's market, just a 15 minute drive. Most of the furnishings and decor are proudly from small businesses in Knoxville. Our favorite is the bathroom door from a local antiquities shop!",
    "text_type": "Human",
    "text_word_count": 76,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "New Haven, CT",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in New Haven, CT with the title \" Cozy cottage in historic neighborhood \" including a detail about the location.",
    "text_stimuli (title)": "Cozy cottage in historic neighborhood",
    "text_stimuli": "Charming 1940s cottage nestled in New Haven's coveted East Rock neighborhood, just steps from East Rock Park's hiking trails. This 2-bedroom home features a wood-burning fireplace, updated kitchen with farmhouse sink, and a peaceful screened-in porch perfect for morning coffee. Original built-ins and exposed beams maintain historic character. Located 1.5 miles from Yale University campus. Perfect for 4 guests. The private backyard garden offers a tranquil retreat with native plants and a stone patio.",
    "text_type": "AI",
    "text_word_count": 74,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Fargo, ND",
    "text_prompt": "NA",
    "text_stimuli (title)": "Heated Garage | Prime Location | Easy Access",
    "text_stimuli": "Relax in our newly renovated 3 bedroom 2 bath home. We have created a modern and inviting atmosphere that will make you feel right at home.\nWe are located in a quite and established neighborhood, close to parks and bike trails, in an up-and-coming part of town. Our home offers the perfect balance between serenity and convenience.\nAs a local host I would love to share my favorite eats and attractions, so shoot me a message!",
    "text_type": "Human",
    "text_word_count": 76,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Lynn, MA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Lynn, MA with the title \" Condo at the Beach : Queen Bed\" including a detail about the location.",
    "text_stimuli (title)": "Condo at the Beach: Queen Bed",
    "text_stimuli": "Positioned directly on Lynn Shore Drive, this contemporary second-story condo delivers pristine Atlantic Ocean and Boston skyline vistas. Situated mere steps from Lynn Beach's historic seawall, this 600-square-foot haven combines beachy modern design with a private viewing balcony ideal for morning sunrises over Nahant Bay. Located only 20 minutes from Boston's center, the property offers convenient access to local dining, green spaces, and public transportation.",
    "text_type": "AI",
    "text_word_count": 71,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Billings, MT",
    "text_prompt": "NA",
    "text_stimuli (title)": "Farmhouse Cottage @ Old Pine Retreats",
    "text_stimuli": "This is your house if you are looking to experience the beauty of rugid Montana landscape just minutes outside of Billings, while in a uniquely designed tiny home. The Farmhouse Cottage @ Old Pine Retreats is a rustic, farmhouse themed home that is loaded with breathtaking views. Guests can take in the landscape next to the wall of windows and fireplace in the living room or enjoy a meal with friends on the main level deck. If this isn't enough, there is a roof-top deck that is sure to please!",
    "text_type": "Human",
    "text_word_count": 89,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Las Cruces, NM",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Las Cruces, NM with the title \" Desert Peaks Casita \" including a detail about the location.",
    "text_stimuli (title)": "Desert Peaks Casita",
    "text_stimuli": "Tucked into the Organ Mountains' gentle slopes, this traditional adobe casita presents 700 square feet of genuine New Mexican character. Situated a quick 15-minute drive from historic Mesilla Plaza, this retreat boasts sweeping desert panoramas and immediate trail access. A secluded courtyard featuring a traditional kiva fireplace offers pristine night-sky viewing, while the comfortable interior highlights authentic vigas, hand-laid Saltillo tiles, and regional art pieces, complemented by newly installed solar panels and desert-wise perennial landscaping.",
    "text_type": "AI",
    "text_word_count": 75,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Evansville, IN",
    "text_prompt": "NA",
    "text_stimuli (title)": "Hobbit House 2 bedroom.",
    "text_stimuli": "Welcome to the Hobbit House! Relax or work from home in this cozy house located in a charming, quiet neighborhood in central Evansville. Each room is curated to set a different vibe from relaxation, sophistication, and fun. This house also has an old speakeasy downstairs filled with arcade games and a movie projector and screen. At night relax in the backyard under a beautifully lit gazebo. This house is also equipped with an office set up to make it easy to work from your home away from home.",
    "text_type": "Human",
    "text_word_count": 88,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "South Bend, IN",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in South Bend, IN with the title \" Charming Farm Retreat Awaits! \" including a detail about the design.",
    "text_stimuli (title)": "Charming Farm Retreat Awaits!",
    "text_stimuli": "This beautifully transformed 1920s barn showcases dramatic 20-foot vaulted ceilings with preserved timber beams and authentic barnwood accents throughout its 900-square-foot layout. The carefully curated interior blends country charm with contemporary farmhouse elegance, featuring classic barn door hardware, artfully displayed agricultural antiques, and handcrafted metalwork. An intimate loft sleeping space peers over the living area, while expansive windows capture serene rural vistas and create a light-filled space perfect for modern country living and pastoral enjoyment.",
    "text_type": "AI",
    "text_word_count": 75,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Longview, TX",
    "text_prompt": "NA",
    "text_stimuli (title)": "Piney Point A-Frame Retreat Tyler",
    "text_stimuli": "Created to share the uniqueness of East Texas with others, Piney Point is a perfect couple or friend's retreat. Tucked in the corner of a six-acre homestead, this restored A-frame offers a modern cozy stay with an expansive deck that overlooks the spring-fed pond. Nearby are some of the best adventures East Texas has to offer, from hiking trails and fishing at Tyler State park, live music, downtown breweries, to market shopping and great food. Escape to the quiet to rest and recharge.",
    "text_type": "Human",
    "text_word_count": 83,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Greeley, CO",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Greeley, CO with the title \" Glenmere Park Bungalow \" including a detail about the design.",
    "text_stimuli (title)": "Glenmere Park Bungalow",
    "text_stimuli": "This artfully designed 1940s bungalow showcases original craftsman details with a modern twist. Featuring exposed wooden beams, custom built-ins, and restored hardwood floors throughout. The two-bedroom home boasts mid-century modern furnishings, local artwork, and large windows flooding the space with natural light. A cozy reading nook with window seat offers views of the historic neighborhood's mature trees. The updated kitchen maintains vintage charm with subway tile backsplash and original glass-front cabinets. The spacious front porch features handcrafted Adirondack chairs perfect for enjoying morning coffee or evening relaxation.",
    "text_type": "AI",
    "text_word_count": 87,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Killeen, TX",
    "text_prompt": "NA",
    "text_stimuli (title)": "Cozy Townhome Retreat",
    "text_stimuli": "Welcome to our exceptional living space in Killeen, Texas. Our accommodations provide a modern, hotel-style experience coupled with the warmth and coziness of a true home away from home. Conveniently located mere minutes from Killeen-Fort Hood Regional Airport, Central Texas College, Texas A&M University Central Texas, AdventHealth Central Texas, Fort Cavazos, HEB, Walmart, and more, our prime location ensures ease of access to all your needs.",
    "text_type": "Human",
    "text_word_count": 66,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Wylie, TX",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Wylie, TX with the title \"Ballard Bungalow in Downtown Wylie\" including a detail about amenities.",
    "text_stimuli (title)": "Ballard Bungalow in Downtown Wylie is a charming 1940s home thoughtfully updated for modern comfort. This cozy retreat features premium amenities including a fully-equipped smart kitchen with Nespresso machine, high-speed fiber internet, and a dedicated workspace. The living room offers a 55\" smart TV with streaming services, while the private backyard features a covered patio with string lights, gas grill, and comfortable lounge seating.",
    "text_stimuli": "This beautifully restored 1920s bungalow combines historic charm with modern luxury in the heart of Wylie. The two-bedroom home features a gourmet kitchen with quartz countertops, stainless appliances, and a fully stocked Keurig coffee station. Enjoy the smart home features, including Nest thermostat, Ring security, and high-speed WiFi throughout. The private backyard offers a covered patio, fire pit, and comfortable outdoor seating for evening relaxation and outdoor dining. Perfect for families or business travelers seeking a comfortable home away from home.",
    "text_type": "AI",
    "text_word_count": 81,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Palm Bay, FL",
    "text_prompt": "NA",
    "text_stimuli (title)": "The Sandhill Blue House",
    "text_stimuli": "Welcome to our newly remodeled South West Palm Bay retreat! Fresh updates, new beds, eco-friendly appliances, well-equipped kitchen, Wi-Fi, Netflix, and a central location near attractions. Book now for a memorable Florida stay! If you are an outdoor loving person there is so much to do from camping, to fishing, airboat rides, and trail/nature walks. The beach is just 35 minutes away, and close to other award wining beaches such as Cocoa Beach. We have one of the best Zoo's in the nation.",
    "text_type": "Human",
    "text_word_count": 83,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Montpelier, VT",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Montpelier, VT with the title \" Cozy Cabin -Top of Hill with Views\" including a detail about the location.",
    "text_stimuli (title)": "Cozy Cabin -Top of Hill with Views",
    "text_stimuli": "Top of Hill with Views sits perched on a scenic hilltop just 10 minutes from downtown Montpelier's charming State Street. This secluded retreat offers panoramic views of the Worcester Mountain Range and Camel's Hump. The cabin's elevated position provides stunning sunrise vistas across the rolling Vermont countryside, while maintaining easy access to the capital city's restaurants and shops. A private wooded trail connects to the property, featuring thoughtfully placed benches and native wildflower gardens along its winding path.",
    "text_type": "AI",
    "text_word_count": 78,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Saginaw, MI",
    "text_prompt": "NA",
    "text_stimuli (title)": "Cozy A-Frame with Hot Tub",
    "text_stimuli": "Cozy, moody A-Frame cabin in the Great Lakes Bay area. Perfect for a couple or small group getaway. This unique space makes you want to relax all day in your pjs and a cup of coffee. It's also close to everything, making it easy to plan your visit - only 5 minutes to downtown bay city shopping, restaurants, and coffee shops. Only 25 minutes to Frankenmuth and 10 minutes to beach - Lake Huron.",
    "text_type": "Human",
    "text_word_count": 72,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Jackson, MS",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Jackson, MS with the title \"The Urban Getaway including a detail about its location.",
    "text_stimuli (title)": "The Urban Getaway",
    "text_stimuli": "A sophisticated three-story townhouse nestled in Jackson's historic Fondren District, just steps from the area's trendiest restaurants and art galleries. This renovated 1920s property sits directly across from Fondren Park, offering convenient access to the neighborhood's vibrant cultural scene. Featuring four bedrooms, a rooftop terrace with city views, and a private courtyard, this urban retreat combines Southern charm with modern luxury while maintaining walking distance to local hotspots. The property boasts original hardwood floors and custom-built shelving.",
    "text_type": "AI",
    "text_word_count": 77,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Auburn, AL",
    "text_prompt": "NA",
    "text_stimuli (title)": "Charming Home- Near Auburn U, Downtown, and RTJ!",
    "text_stimuli": "Escape to this charming 3-bedroom, 2-bathroom home located just minutes away from the RTJ Golf Trail! Perfect for families or groups of friends, this home boasts comfortable furnishings, modern amenities, and a fabulous large porch out back. Take advantage of the premium location as you cheer on the Auburn Tigers, with the Tiger Transit bus stop for games on campus just across the street. Book your stay today and enjoy a relaxing getaway in the heart of Auburn!",
    "text_type": "Human",
    "text_word_count": 78,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Danville, VA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Danville, VA with the title \"Large Luxe 4 BR w Basement suite, Bar & Game Room\" including a factor about amenities.",
    "text_stimuli (title)": "Large Luxe 4 BR w Basement suite, Bar & Game Room",
    "text_stimuli": "Historic 1920s mansion transformed into a 4-bedroom luxury retreat in Danville's Old West End district. Features original hardwood floors, gourmet kitchen with Viking appliances, and a basement entertainment paradise including full wet bar, pool table, and arcade games. Master suite boasts a clawfoot tub and private balcony. Smart home features throughout, including Nest thermostats and keyless entry. Sleeps 10 comfortably. Walking distance to the trendy River District's restaurants and breweries.",
    "text_type": "AI",
    "text_word_count": 70,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Schenectady, NY",
    "text_prompt": "NA",
    "text_stimuli (title)": "Cozy Winter Getaway w/ Fireplaces : 1850 Farmhouse",
    "text_stimuli": "Nestled in a serene, wooded hillside with views of the Catskill Mountains, this solar-powered cottage is a cozy, perfect getaway to forget your busy life and reconnect with beautiful nature. Our tiny house is close to many attractions: 25 min away from Windham Mountain, famous for winter activities, 15-20 min away from numerous state parks & nearly 200 acres of preserves, and less than 45 min away from Catskill and Hudson.",
    "text_type": "Human",
    "text_word_count": 70,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Elyria, OH",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Elyria, OH with the title \"The Farmer's Cottage\" including a factor about amenities.",
    "text_stimuli (title)": "The Farmer's Cottage",
    "text_stimuli": "A charming restored 1800s farmhouse in Elyria's historic rural district, featuring modern amenities while preserving its rustic character. The property's standout feature is its fully-equipped gourmet kitchen with a restored vintage AGA stove, professional-grade appliances, and a custom butcher block island. Three cozy bedrooms, a wraparound porch with rocking chairs, and a private hot tub make this cottage perfect for both relaxation and culinary adventures. The property also includes complimentary farm-fresh eggs and seasonal produce from the working garden.",
    "text_type": "AI",
    "text_word_count": 79,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  }
]