var assessment_stim_multifeatured = [
  {
    "Initials": "AL",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Grand Prarie, TX",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Grand Prairie, TX with the title Chic 2Bed 1Bath House Near AT&T Stadium including its closeness to the Naval Air Station",
    "text_stimuli (title)": "Chic 2Bed 1Bath House Near AT&T Stadium",
    "text_stimuli": "Experience comfort and style in this beautifully updated 2-bedroom, 1-bathroom vacation rental in Grand Prairie, TX. Located just 10 minutes from AT&T Stadium and 15 minutes from the Naval Air Station, it's an ideal spot for sports enthusiasts and military guests. The home features a modern kitchen, inviting living space, and luxurious bedding. Enjoy the private patio with a BBQ grill, while being close to shopping, dining, and entertainment for a convenient and enjoyable stay.",
    "text_type": "AI",
    "text_word_count": 75,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing:",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_grandprarie.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/11.S.W.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Boulder, Colorado",
    "text_prompt": "NA",
    "text_stimuli (title)": "Secluded modern mountain home with stunning view",
    "text_stimuli": "A tranquil and luxurious retreat 25 minutes (10 miles) from downtown Boulder. Enjoy ultimate seclusion at the end of a mile long private gravel driveway surrounded by hundreds of acres of open space. Star gaze from the hot tub, cook gourmet meals in the spacious kitchen, or just sit on the sofa, sip on a cappuccino, and watch clouds form over the mountains through the 17 foot high glass wall.",
    "text_type": "Human",
    "text_word_count": 70,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_boulder.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/4.R.SA.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "AL",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Kansas City, MO",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Kansas City, MO with the title Cozy Cottage in the heart of Kansas City including its 1940s cottage charm",
    "text_stimuli (title)": "Charming 1940s Cottage",
    "text_stimuli": "Step back in time at this charming 1940s cottage nestled in Kansas City's lively urban core. This beautifully restored gem features vintage decor, original hardwood floors, and a quaint fireplace for ultimate comfort. Modern updates include a fully equipped kitchen and luxurious linens. Enjoy the private garden patio, perfect for morning coffee, evening wine, or relaxation. Located minutes from Westport and the Plaza, it's an ideal retreat blending old-world charm with city convenience and modern amenities.",
    "text_type": "AI",
    "text_word_count": 72,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing:",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_kansascity1.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/22.S.SA.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Lakewood, CO",
    "text_prompt": "NA",
    "text_stimuli (title)": "Lakewood Solar Home Retreat",
    "text_stimuli": "Beautiful, sustainable, all solar home with lots of windows and a view of the mountains in a safe farm-y neighborhood served by Uber, 10 min. from Red Rocks Amphitheater, the charming town of Morrison, Dinosaur Ridge, Bear Creek Lake, hiking/biking and the Rocky Mountains, just 20 min. from downtown Denver, the Broncos, Rockies, etc. Your suite is the lower level of our home with a private entrance & patio . No smokingócigarettes, vaping, or marijuana. No Pets or animals.",
    "text_type": "Human",
    "text_word_count": 77,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_lakewood.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/47.R.W.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "AL",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Cape Coral, Fl",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Cape Coral, FL with the title Heated Pool on Honeymoon Lake including its heated pool",
    "text_stimuli (title)": "Heated Pool on Honeymoon Lake",
    "text_stimuli": "Discover your perfect escape at this tranquil Cape Coral retreat, boasting a heated pool with stunning Honeymoon Lake views. This inviting home features three comfortable bedrooms, an airy open-concept living space, and floor-to-ceiling windows framing the serene waterfront. Relax by the pool, fish from the private dock, or dine outdoors on the spacious lanai. Close to pristine beaches, vibrant dining, and local attractions, this getaway promises a peaceful and unforgettable Florida vacation experience.",
    "text_type": "AI",
    "text_word_count": 73,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing:",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_capecoral.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/8.S.B.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "St. Louis, MO",
    "text_prompt": "NA",
    "text_stimuli (title)": "Little Red House, Entire House in Tower Grove East",
    "text_stimuli": "This 2 Bedroom 1 Bath home is centrally located in Tower Grove East, 5 minutes from St. Louis University, 8 minutes from Grand Center and just a few short blocks from hip South Grand and Tower Grove. It is the entire house, no neighbors to bother you. The block is quiet and the neighbors are friendly but please note this house is located in an urban area. While generally safe it is racially and economically mixed. Please set your expectations accordingly.",
    "text_type": "Human",
    "text_word_count": 81,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_stlouis.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/36.R.B.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "AL/SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "San Francisco, CA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in San Francisco, CA with the title La Casita - a quiet studio, Crocker Amazon area including it is a detached studio",
    "text_stimuli (title)": "La Casita - Quiet Detached Studio in Crocker Amazon",
    "text_stimuli": "Tucked away in the peaceful Crocker Amazon neighborhood of San Francisco, La Casita is a charming detached studio perfect for a quiet escape. This cozy space includes a comfortable queen bed, a private kitchenette, and a lovely garden patio for relaxing. Located near local cafes, beautiful parks, and convenient public transportation, it's an ideal retreat for solo travelers or couples seeking tranquility while staying connected to the city's lively attractions.",
    "text_type": "AI",
    "text_word_count": 70,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\"\nLa Casita - Quiet Detached Studio in Crocker Amazon\nTucked away in the peaceful Crocker Amazon neighborhood of San Francisco, La Casita is a charming detached studio perfect for a quiet escape. This cozy space includes a comfortable queen bed, a private kitchenette, and a lovely garden patio for relaxing. Located near local cafes, beautiful parks, and convenient public transportation, it's an ideal retreat for solo travelers or couples seeking tranquility while staying connected to the city's lively attractions.\"].",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_sanfrancisco.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini (2.0 Flash)",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/9.S.SA.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Charlotte, NC",
    "text_prompt": "NA",
    "text_stimuli (title)": "A-Frame of Mind & 30 min from city. Free Breakfast",
    "text_stimuli": "Take it easy at this unique and tranquil getaway. Enjoy the peacefulness and serenity, while being only 30 min away from the city. Nestled in Mint Hill area , this beautiful and unique A-Frame house been fully renovated and equipped to entertain and to never disappoint. Escape to fresh air , warm fire and starry nights. Breakfast is provided. The house accommodates 6 adults 2 kids, only 1 shower.",
    "text_type": "Human",
    "text_word_count": 68,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_charlotte.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/22.R.SA.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "AL/SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Denver, CO",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Denver, CO with the title Charming carriage house w/ private patio including its private garden patio",
    "text_stimuli (title)": "Cozy Carriage House w/ Private Garden Patio",
    "text_stimuli": "Discover a peaceful Denver getaway in this charming carriage house tucked into a quiet neighborhood. Blending modern comfort with rustic flair, it features a fully equipped kitchenette, a cozy lofted bedroom, and inviting, vibrant decor. Step onto your private garden patio, a tranquil space perfect for sipping coffee or unwinding in the evening. Conveniently located just minutes from downtown and top attractions, this delightful retreat offers an ideal balance of relaxation and accessibility.",
    "text_type": "AI",
    "text_word_count": 73,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\"\nCozy Carriage House w/ Private Garden Patio\nDiscover a peaceful Denver getaway in this charming carriage house tucked into a quiet neighborhood. Blending modern comfort with rustic flair, it features a fully equipped kitchenette, a cozy lofted bedroom, and inviting, vibrant decor. Step onto your private garden patio, a tranquil space perfect for sipping coffee or unwinding in the evening. Conveniently located just minutes from downtown and top attractions, this delightful retreat offers an ideal balance of relaxation and accessibility.\"].",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_denver.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini (2.0 Flash)",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/7.S.SA.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Seattle, WA",
    "text_prompt": "NA",
    "text_stimuli (title)": "The Pacific Northwest Getaway",
    "text_stimuli": "Eat, sleep and be in the forest.  A cocoon of luxury located in the heart of the Pacific Northwest.  One of the best locations to experience everything the PNW has to offer.     Get a good nights rest and then head out to explore! Seattle (20mi) SeaTac Intl Airport (17mi), Bellevue (15 mi), DT Issaquah (4 mi), Mt. Rainier Nat'l Park (44 mi), Snoqualmie Falls (16 mi) Chateau Ste. Michelle Winery (24 mi), Snoqualmie Pass (42 mi) Crystal Mountain Ski Resort (63 mi)",
    "text_type": "Human",
    "text_word_count": 82,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_seattle.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/29.R.W.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "AL/SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Boston, MA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Boston, MA with the title 1850s Charlestown Cottage including the short walk to the Boston Harbor",
    "text_stimuli (title)": "1850s Charlestown Cottage",
    "text_stimuli": "Experience the charm of Boston's history at this delightful 1850s Charlestown Cottage. Located in the heart of Charlestown, this two-bedroom retreat blends original details like exposed brick and vintage decor with modern comforts. Relax on the secluded patio or take a short walk to the picturesque Boston Harbor. Perfectly situated near the Freedom Trail and local eateries, this cozy cottage offers a unique mix of historical ambiance and contemporary convenience for your stay.",
    "text_type": "AI",
    "text_word_count": 73,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\"\n1850s Charlestown Cottage\nExperience the charm of Boston's history at this delightful 1850s Charlestown Cottage. Located in the heart of Charlestown, this two-bedroom retreat blends original details like exposed brick and vintage decor with modern comforts. Relax on the secluded patio or take a short walk to the picturesque Boston Harbor. Perfectly situated near the Freedom Trail and local eateries, this cozy cottage offers a unique mix of historical ambiance and contemporary convenience for your stay.\"].",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_boston.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini (2.0 Flash)",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/43.S.EA.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Washington, DC",
    "text_prompt": "NA",
    "text_stimuli (title)": "Beautiful 2br / 2ba carriage house with parking",
    "text_stimuli": "Welcome to our beautiful carriage house in centrally-located Mt Pleasant! The unit is fully renovated, private, and filled with sunlight & charming details. Enjoy a big living area, full kitchen, 2 bedrooms, 2 full baths, W/D & comfortable queen sofa bed. Kids will love the adorable nook bedroom! Great location: 5-10 min walk to Metro, National Zoo, restaurants & cafes, and beautiful Rock Creek Park (with endless trails). 15 min drive or bike to downtown / museums. On-site parking available.",
    "text_type": "Human",
    "text_word_count": 76,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_washingtondc.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/41.R.B.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Cleveland, OH",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Cleveland, OH with the title Come stay on Flamingo Ave including being close to Fairview Hospital",
    "text_stimuli (title)": "Come Stay on Flamingo Ave!",
    "text_stimuli": "Experience cozy comfort at this chic vacation rental in Cleveland, OH. Nestled on the charming Flamingo Ave, this stylish home boasts vibrant, modern decor with tropical-inspired touches. Just minutes from Fairview Hospital, it's perfect for visiting loved ones, medical professionals, or business travelers. Enjoy a spacious living area, fully equipped kitchen, private backyard oasis, and free parking. Conveniently located near local dining, shopping, and parks, it's an ideal retreat for relaxation, exploration, and memorable stays alike.",
    "text_type": "AI",
    "text_word_count": 72,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\"\nCome Stay on Flamingo Ave\nExperience cozy comfort at this chic vacation rental in Cleveland, OH. Nestled on the charming Flamingo Ave, this stylish home boasts vibrant, modern decor with tropical-inspired touches. Just minutes from Fairview Hospital, it's perfect for visiting loved ones or medical professionals. Enjoy a spacious living area, fully equipped kitchen, private backyard oasis, and free parking. Conveniently located near local dining, shopping, and parks, it's an ideal retreat for relaxation and exploration alike.\"].",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_cleveland.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage (General Fast -- Stable Diffusion XL)",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/21.S.W.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Wichita, KS",
    "text_prompt": "NA",
    "text_stimuli (title)": "Tiny Home Route66/Vintage, spacious bathroom",
    "text_stimuli": "Have you ever wanted to experience the Tiny House revolution. Here is your chance to stay in a home with main floor sleeping, spacious bathroom to rival any hotel or home, all the amenities you need plus a great patio for enjoying the fresh air. This home has a Route 66 theme, from the decorations to the Red fridge past the retro toy trucks. Enjoy this small home with big character.",
    "text_type": "Human",
    "text_word_count": 70,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_wichita.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/6.R.EA.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Aurora, CO",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Aurora, CO with the title La Casita Suite Close to Airport & The Southlands including its proximity to Denver.",
    "text_stimuli (title)": "La Casita Suite Close to Airport & The Southlands",
    "text_stimuli": "Nestled in a quiet Aurora neighborhood, La Casita Suite is a cozy, modern retreat just 15 minutes from Denver International Airport and 10 minutes from The Southlands shopping district. This private suite features a plush queen bed, a stylish kitchenette, and a spa-like bathroom. Guests enjoy easy access to downtown Denver (30 minutes away), local hiking trails, and top dining spots. Perfect for travelers seeking comfort, convenience, and a touch of charm!",
    "text_type": "AI",
    "text_word_count": 72,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\"\nLa Casita Suite Close to Airport & The Southlands\n\nNestled in a quiet Aurora neighborhood, La Casita Suite is a cozy, modern retreat just 15 minutes from Denver International Airport and 10 minutes from The Southlands shopping district. This private suite features a plush queen bed, a stylish kitchenette, and a spa-like bathroom. Guests enjoy easy access to downtown Denver (30 minutes away), local hiking trails, and top dining spots. Perfect for travelers seeking comfort, convenience, and a touch of charm!\"].",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_aurora.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage (General Fast -- Stable Diffusion XL)",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/23.S.B.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Bakersfield, CA",
    "text_prompt": "NA",
    "text_stimuli (title)": "Cozy Camino Retreat",
    "text_stimuli": "Visiting family, temporary work, or just want a place to stay in relax in the city? Camino Primavera Retreat is the perfect place for you and your family. Kick back and relax in this calm, stylish mid-century style home with large beautiful windows and peaceful vibes. The large living room windows invite you into a peaceful backyard surrounded by trees and landscaping. You're just a few minutes drive away from Chipotle, Starbucks, Target, Smart & Final and so much more!",
    "text_type": "Human",
    "text_word_count": 79,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_bakersfield.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/44.R.B.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Honolulu, HI",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Honolulu, HI with the title Waikiki Ocean & Sunset Views w/ Free Parking including being near the Waikiki beach",
    "text_stimuli (title)": "Waikiki Ocean & Sunset Views w/ Free Parking",
    "text_stimuli": "Discover the perfect getaway at this stunning Honolulu vacation rental. Located steps from iconic Waikiki Beach, this modern oasis features panoramic ocean and sunset views from a private lanai. The thoughtfully designed interior includes a sleek kitchen, comfortable living area, and serene bedroom. Enjoy resort-style amenities, including a pool, fitness center, and a relaxing hot tub. With free parking and proximity to vibrant dining, shopping, and nightlife, it's the ideal spot for a tropical escape, adventure, and unforgettable relaxation experience!",
    "text_type": "AI",
    "text_word_count": 80,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: Discover the perfect getaway at this stunning Honolulu vacation rental. Located steps from iconic Waikiki Beach, this modern oasis features panoramic ocean and sunset views from a private lanai. The thoughtfully designed interior includes a sleek kitchen, comfortable living area, and serene bedroom. Enjoy resort-style amenities, including a pool, fitness center, and a relaxing hot tub. With free parking and proximity to vibrant dining, shopping, and nightlife, it's the ideal spot for a tropical escape, adventure, and unforgettable relaxation experience!",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_honolulu.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage (General Fast -- Stable Diffusion XL)",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/1.S.B.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Stanton, CA",
    "text_prompt": "NA",
    "text_stimuli (title)": "Comfort Private House Close to Many Attractions",
    "text_stimuli": "Only 0.9 miles from Disneyland , 2-5 mints by car, 10-15 mints walk, this Cul De Sac home is on a tree-lined, quiet and safe street. After a long day of walking in Disneyland, you will really enjoy the sparkling hot spa and comfy beds of this clean, cozy house. It is walking distance to Disneyland. Equipped with big TVs, 2 sets of dining areas to host guests, and a cute backyard with a deck and chairs to relax. High quality white linens, double layers of curtains give you a good sleep.",
    "text_type": "Human",
    "text_word_count": 75,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_stanton.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/5.R.W.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Chandler, AZ",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Chandler, Arizona with the title Sparkling Clean, Downtown Chandler Oasis including a private pool",
    "text_stimuli (title)": "Sparkling Clean, Downtown Chandler Oasis",
    "text_stimuli": "Escape to this modern vacation rental in the heart of Downtown Chandler! This pristine, stylish retreat features a private sparkling pool surrounded by lush landscaping, a fire pit, and a cozy outdoor lounge. Inside, enjoy sleek furnishings, a gourmet kitchen, and three spacious bedrooms with luxury linens. Walk to local eateries, breweries, and shops just minutes away. Perfect for families or small groups seeking relaxation and urban charm, this oasis guarantees an unforgettable getaway.",
    "text_type": "AI",
    "text_word_count": 74,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\"\nSparkling Clean, Downtown Chandler Oasis\n\nEscape to this modern vacation rental in the heart of Downtown Chandler! This pristine, stylish retreat features a private sparkling pool surrounded by lush landscaping, a fire pit, and a cozy outdoor lounge. Inside, enjoy sleek furnishings, a gourmet kitchen, and three spacious bedrooms with luxury linens. Walk to local eateries, breweries, and shops just minutes away. Perfect for families or small groups seeking relaxation and urban charm, this oasis guarantees an unforgettable getaway.\"].",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_chandler.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini (2.0 Flash)",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/48.S.W.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Union, NJ",
    "text_prompt": "NA",
    "text_stimuli (title)": "Modern 3BR/2BA - 10min to EWR, 30min to NYC",
    "text_stimuli": "Feel right at home in this freshly renovated 3 bedroom, 2 bathroom unit (second floor) conveniently located near major roads, Newark Airport, and Jersey Garden Mall. This beautifully styled home provides easy access to NYC via bus, train or car. Better than a hotel and a terrific value you won't find anywhere else in this area. The neighborhood has a wide variety of bars & restaurants a within 2 blocks. Convenient, centrally located in the neighborhood!",
    "text_type": "Human",
    "text_word_count": 75,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_union.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/48.R.W.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Lubbock, TX",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Lubbock, TX with the title Big Basement Gameroom: The Kiyo by Spark Getaways including a two car garage",
    "text_stimuli (title)": "Big Basement Gameroom: The Kiyo by Spark Getaways",
    "text_stimuli": "This one-of-a-kind vacation rental in Lubbock, TX features a spacious basement gameroom complete with a pool table, arcade games, and a cozy movie lounge. The modern three-bedroom home offers comfort with premium bedding, a fully stocked kitchen, and vibrant decor inspired by Texas charm. Guests enjoy the convenience of a two-car garage and a private backyard perfect for relaxing or grilling. Located minutes from Texas Tech and local hotspots, it's ideal for families and groups.",
    "text_type": "AI",
    "text_word_count": 75,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\"\nBig Basement Gameroom: The Kiyo by Spark Getaways\n\nThis one-of-a-kind vacation rental in Lubbock, TX features a spacious basement gameroom complete with a pool table, arcade games, and a cozy movie lounge. The modern three-bedroom home offers comfort with premium bedding, a fully stocked kitchen, and vibrant decor inspired by Texas charm. Guests enjoy the convenience of a two-car garage and a private backyard perfect for relaxing or grilling. Located minutes from Texas Tech and local hotspots, it's ideal for families and groups.\"].",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_lubbock.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini (2.0 Flash)",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/1.S.EA.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Madison, WI",
    "text_prompt": "NA",
    "text_stimuli (title)": "Historic guesthouse near downtown, hospital and UW",
    "text_stimuli": "Featured on the National Register of Historic Places, this unique 1916 \"granny cottage\" stands behind our home in the gorgeous Village of Shorewood Hills. Centrally located, we are just a few walkable blocks from UW Hospital and Picnic Point, and walking/biking distance from UW, the Capitol, Hilldale Shopping Mall, Whole Foods and plenty of restaurants. Because we are in a quiet neighborhood, we have a 3 guest maximum. This is a place to retreat and relax and enjoy the best of Madison.",
    "text_type": "Human",
    "text_word_count": 82,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_madison.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/7.R.W.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Nevada City, CA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Nevada City, CA with the title Harmony Mountain Retreat including its proximity to ski slopes",
    "text_stimuli (title)": "Harmony Mountain Retreat",
    "text_stimuli": "Harmony Mountain Retreat is a serene vacation rental nestled in the Sierra Nevada foothills, just 30 minutes from Tahoe National Forest's renowned ski slopes. This modern yet rustic cabin features panoramic mountain views, a private hot tub, and a cozy fireplace. The three-bedroom retreat includes a fully equipped kitchen, outdoor dining area, and walking trails through nearby pine forests. Ideal for skiers, nature enthusiasts, and relaxation seekers, it's the perfect blend of adventure and tranquility.",
    "text_type": "AI",
    "text_word_count": 75,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\"\nHarmony Mountain Retreat is a serene vacation rental nestled in the Sierra Nevada foothills, just 30 minutes from Tahoe National Forest's renowned ski slopes. This modern yet rustic cabin features panoramic mountain views, a private hot tub, and a cozy fireplace. The three-bedroom retreat includes a fully equipped kitchen, outdoor dining area, and walking trails through nearby pine forests. Ideal for skiers, nature enthusiasts, and relaxation seekers, it's the perfect blend of adventure and tranquility.\"].",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_nevadacity.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini (2.0 Flash)",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/17.S.W.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Scottsdale, AZ",
    "text_prompt": "NA",
    "text_stimuli (title)": "Backyard Oasis w/ Heated Pool | Bike 2 Old Town",
    "text_stimuli": "Experience luxury and relaxation at 87th Place by Great AZ Stays, a modern vacation home located just minutes from Old Town Scottsdale. The private resort-style backyard offers a lovely heated pool, loungers, a fire pit and plenty of backyard games. This 3 bedroom desert oasis includes a fully-stocked and updated kitchen, comfortable furnishings and a convenient location making it perfect for families, friends, and couples to have a memorable stay in Arizona.",
    "text_type": "Human",
    "text_word_count": 72,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_scottsdale.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/20.R.SA.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Nampa, ID",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Nampa, ID with the title \" Cottage In Nampa \" including a detail about the location.",
    "text_stimuli (title)": "Cottage In Nampa",
    "text_stimuli": "This charming 1940s brick cottage sits in Nampa's historic North District, just two blocks from the antique shops of downtown. The fully renovated 2-bedroom home features original hardwood floors, a gourmet kitchen with farmhouse sink, and a private backyard garden with lavender beds. The cottage's wraparound porch offers views of the Nampa Train Depot's iconic clock tower. The home's location provides easy access to the Nampa Farmers Market and the Ford Idaho Center's year-round events.",
    "text_type": "AI",
    "text_word_count": 75,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: This charming 1940s brick cottage sits in Nampa's historic North District, just two blocks from the antique shops of downtown. The fully renovated 2-bedroom home features original hardwood floors, a gourmet kitchen with farmhouse sink, and a private backyard garden with lavender beds. The cottage's wraparound porch offers views of the Nampa Train Depot's iconic clock tower. The home's location provides easy access to the Nampa Farmers Market and the Ford Idaho Center's year-round events.",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_nampa.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/16.S.EA.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": 0,
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Kalamazoo, MI",
    "text_prompt": "NA",
    "text_stimuli (title)": "Tiny house, a cozy winter getaway by I-94",
    "text_stimuli": "Enjoy a cozy stay that is close to Kalamazoo's restaurants and attractions. On 22 acres with trails near Al Sabo Land Preserve. Beautiful and picturesque view of property from the living room space. The apartment is fully furnished with linens and dishes. Just bring yourself and your suitcase. There is a queen mattress ready for your peaceful slumber on the loft and also a sleeper sofa on the main floor.",
    "text_type": "Human",
    "text_word_count": 70,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_kalamazoo.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/23.R.B.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Charleston, SC",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Charleston, SC with the title \" Bright, Airy Charleston Home w/ Big Backyard\" including a detail about the amenities.",
    "text_stimuli (title)": "Bright, Airy Charleston Home w/ Big Backyard",
    "text_stimuli": "This updated 1,200-square-foot lowcountry retreat boasts elegant 12-foot ceilings, preserved heart pine flooring, and towering windows bathing the interior in sunlight. The chef's kitchen features bespoke cabinetry, marble surfaces, and premium appliances. A secluded outdoor sanctuary offers a breezy screened veranda with overhead fans, alfresco cooking space, and a peaceful water feature encompassed by flowering camellias and vibrant azalea gardens.",
    "text_type": "AI",
    "text_word_count": 70,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "Create an image of the exterior view of the described vacation rental listing: \"Stunning Couples Cottage with Creek Dock!\"\n\nPositioned on tranquil Shem Creek in Mount Pleasant's coveted Old Village district, this enchanting 600-square-foot hideaway delivers waterfront peace just minutes from Charleston's historic center. The expertly updated cottage includes a personal dock ideal for paddling adventures and wildlife viewing, plus a breezy screened veranda overlooking the water. Situated moments from fresh seafood dining and the historic Pitt Street Bridge, this intimate escape merges coastal allure with contemporary comfort.",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_charleston2.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/49.S.EA.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": 0,
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Murfreesboro, TN",
    "text_prompt": "NA",
    "text_stimuli (title)": "Charming Home Close to Downtown",
    "text_stimuli": "Welcome to our beautiful home in the heart of Murfreesboro. This charming remodel of the original SH Stacey store offers a comfortable and memorable stay, combining modern amenities with the character and history of the area. With its convenient location and thoughtful touches, it's the perfect home base for your visit. Walk to MTSU to tour the campus, downtown for dinner, or the Farmers Market on Saturday morning. There is always something fun going on in town!",
    "text_type": "Human",
    "text_word_count": 77,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_murfreesboro.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/8.R.EA.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": 0.2,
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Temecula, CA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Temecula, CA with the title \" Cottage Overlooking Wineries-Panoramic Views\" including a detail about the location.",
    "text_stimuli (title)": "Cottage Overlooking Wineries-Panoramic Views",
    "text_stimuli": "Perched on a hilltop in Temecula's De Portola Wine Trail, this Mediterranean-style cottage offers sweeping views of rolling vineyards and hot air balloons at sunrise. The one-bedroom retreat features a private infinity pool, outdoor kitchen, and floor-to-ceiling windows throughout. Located just minutes from award-winning Wilson Creek Winery, guests can enjoy wine tasting and fine dining within walking distance. A custom stone firepit on the wraparound deck provides the perfect spot for stargazing while enjoying local wines.",
    "text_type": "AI",
    "text_word_count": 76,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: Perched on a hilltop in Temecula's De Portola Wine Trail, this Mediterranean-style cottage offers sweeping views of rolling vineyards and hot air balloons at sunrise. The one-bedroom retreat features a private infinity pool, outdoor kitchen, and floor-to-ceiling windows throughout. Located just minutes from award-winning Wilson Creek Winery, guests can enjoy wine tasting and fine dining within walking distance. A custom stone firepit on the wraparound deck provides the perfect spot for stargazing while enjoying local wines.",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_temecula.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/16.S.SA.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": 0.8,
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Chatham, NJ",
    "text_prompt": "NA",
    "text_stimuli (title)": "Open Concept APT w/ Gym",
    "text_stimuli": "Enjoy a stylish experience at this centrally-located apt in affluent Summit NJ. Only 0.1 miles from a morning walk in Briant Park, 0.9 miles from the famous Baltusrol Golf Course and 0.9 miles from the restaurant/bar life, you'll be able to safely fine dine with friends/loved ones. If you want to branch out, you are only 0.9 miles from the Summit Train station and less than a mile away from route 78 and route 24 allowing easy access to nearby towns/cities to further enhance your experience.",
    "text_type": "Human",
    "text_word_count": 86,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_chatham.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/3.R.W.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Montgomery, AL",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Montgomery, AL with the title \"Sweet Like Tandy\" including a detail about the landscape.",
    "text_stimuli (title)": "Sweet like Tandy",
    "text_stimuli": "This restored 1920s craftsman bungalow sits in Montgomery's historic Garden District, surrounded by centuries-old magnolia trees and manicured azalea gardens. The three-bedroom home features a classic Southern wraparound porch, period antiques, and a gourmet kitchen with original beadboard ceiling. Just steps from the Alabama State Capitol, guests can enjoy rocking chairs overlooking the property's heirloom rose garden. A private courtyard with a bubbling fountain and brick pathways provides a serene space for morning coffee or evening cocktails.",
    "text_type": "AI",
    "text_word_count": 77,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: This restored 1920s craftsman bungalow sits in Montgomery's historic Garden District, surrounded by centuries-old magnolia trees and manicured azalea gardens. The three-bedroom home features a classic Southern wraparound porch, period antiques, and a gourmet kitchen with original beadboard ceiling. Just steps from the Alabama State Capitol, guests can enjoy rocking chairs overlooking the property's heirloom rose garden. A private courtyard with a bubbling fountain and brick pathways provides a serene space for morning coffee or evening cocktails.",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_montgomery.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/30.S.EA.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": 0,
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Mobile, AL",
    "text_prompt": "NA",
    "text_stimuli (title)": "Cozy South Alabama Home",
    "text_stimuli": "Your family will be close to everything when you stay at this centrally-located place. Minutes from South Alabama (USA), Springhill College, Mobile Tennis Center, parks, golf, Mobile Art Museum, Fair Grounds, and much more. The home sits on a large lot easy to find. Large fenced back yard for you and your four legged family members to enjoy. Also has a large covered back deck to enjoy along with a gas grill. Walking distance to the park and Japanese's garden.",
    "text_type": "Human",
    "text_word_count": 80,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_mobile.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/15.R.B.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Des Moines, IA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Des Moines, IA with the title \" New Arrival Forest Escape Luxury \" including a detail about the design.",
    "text_stimuli (title)": "New Arrival Forest Escape Luxury",
    "text_stimuli": "Nestled in Des Moines' Salisbury Forest, this contemporary A-frame features soaring 30-foot windows that seamlessly blend indoor and outdoor living. The architect-designed space showcases exposed Douglas fir beams, polished concrete floors, and a floating staircase leading to the loft bedroom. Just 10 minutes from downtown, guests can enjoy the private deck overlooking a wooded ravine with seasonal creek views. Custom-built window seats with integrated heating provide cozy nooks for watching deer and wild turkeys roam the property.",
    "text_type": "AI",
    "text_word_count": 77,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: Nestled in Des Moines' Salisbury Forest, this contemporary A-frame features soaring 30-foot windows that seamlessly blend indoor and outdoor living. The architect-designed space showcases exposed Douglas fir beams, polished concrete floors, and a floating staircase leading to the loft bedroom. Just 10 minutes from downtown, guests can enjoy the private deck overlooking a wooded ravine with seasonal creek views. Custom-built window seats with integrated heating provide cozy nooks for watching deer and wild turkeys roam the property.",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_desmoines.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/29.S.EA.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": 0,
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Chattanooga, TN",
    "text_prompt": "NA",
    "text_stimuli (title)": "Trendy home in Lively Southside",
    "text_stimuli": "Welcome to Robinson's Nest! This new and beautifully designed three bedroom home is located in a safe, quiet community right off of Main Street in downtown Chattanooga. It offers direct access to coffee shops, restaurants, parks, boutiques, music venues, art galleries, and more! In addition to all Southside has to offer, you'll have downtown tourist destinations right at your fingertips. We really are close to everything!",
    "text_type": "Human",
    "text_word_count": 66,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_chattanooga.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/31.R.EA.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Columbia, SC",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Columbia, SC with the title \" Golden Reflections Getaway\" including a detail about the location.",
    "text_stimuli (title)": "Golden Reflections Getaway",
    "text_stimuli": "\"Golden Reflections Getaway\" is an enchanting lakeside haven situated on the tranquil banks of Lake Murray, a mere half-hour from Columbia's city center. This two-level escape boasts expansive windows that flood the interior with a golden glow at dusk. The spacious main area showcases a cozy stone hearth and country-chic furnishings. A wraparound porch with a bubbling hot tub provides breathtaking water vistas. With exclusive dock access for angling or launching watercraft, this retreat seamlessly melds serenity and excitement, offering the ideal backdrop for a memorable lakeside vacation.",
    "text_type": "AI",
    "text_word_count": 88,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: \"Golden Reflections Getaway\" is an enchanting lakeside haven situated on the tranquil banks of Lake Murray, a mere half-hour from Columbia's city center. This two-level escape boasts expansive windows that flood the interior with a golden glow at dusk. The spacious main area showcases a cozy stone hearth and country-chic furnishings. A wraparound porch with a bubbling hot tub provides breathtaking water vistas. With exclusive dock access for angling or launching watercraft, this retreat seamlessly melds serenity and excitement, offering the ideal backdrop for a memorable lakeside vacation.",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_columbia.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/32.S.W.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": 0.4,
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Grand Rapids, MI",
    "text_prompt": "NA",
    "text_stimuli (title)": "Tiny House In the City",
    "text_stimuli": "Welcome to our tiny home! In 2019 my husband and I set out to renovate this old pool house into a self-sustainable apartment or tiny home. As you can imagineÖ things did not turn out the way we intended and construction was completed in the fall of 2020! We are thrilled to open up a part of our lives and our home to you! The amenities are not lacking within the space and we know you will feel at home!",
    "text_type": "Human",
    "text_word_count": 80,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_grandrapids.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/46.R.SA.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Olympia, WA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Olympia, WA with the title \"Cozy Lake Front Cottage - Family & Pet Friendly!\" including a detail about the property.",
    "text_stimuli (title)": "Cozy Lake Front Cottage - Family & Pet Friendly!",
    "text_stimuli": "Cozy Lake Front Cottage - Family & Pet Friendly!\" is a charming retreat nestled on the shores of Black Lake, just 15 minutes from downtown Olympia, WA. This quaint two-bedroom cottage features a spacious deck overlooking the water, perfect for outdoor dining and stargazing. The property includes a private dock for fishing or launching kayaks, and a fenced yard where pets can roam freely. Inside, a stone fireplace warms the open-concept living area, while large windows offer stunning lake views year-round.",
    "text_type": "AI",
    "text_word_count": 79,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: \"Cozy Lake Front Cottage - Family & Pet Friendly!\" is a charming retreat nestled on the shores of Black Lake, just 15 minutes from downtown Olympia, WA. This quaint two-bedroom cottage features a spacious deck overlooking the water, perfect for outdoor dining and stargazing. The property includes a private dock for fishing or launching kayaks, and a fenced yard where pets can roam freely. Inside, a stone fireplace warms the open-concept living area, while large windows offer stunning lake views year-round.",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_olympia.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage  (General Fast -- Stable Diffusion XL)",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/25.S.B.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Dover, DE",
    "text_prompt": "NA",
    "text_stimuli (title)": "Spacious 5 Bedroom w/Pool, Patio and Theater",
    "text_stimuli": "This large 5 bedroom, 2.5 bathroom home in charming magnolia boasts a large, gourmet kitchen, finished basement, and an inground pool. The large island in the kitchen with an adjoining dining room allows for plenty of space for enjoying meals. The finished basement has a theater and game room perfect for an evening of family fun! The primary bathroom has a large soaker tub, double sinks, and a shower. Make lasting memories with all this home has to offer! No parties allowed at this property.",
    "text_type": "Human",
    "text_word_count": 85,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_dover1.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/17.R.B.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Cheyenne, WY",
    "text_prompt": "Create and describe in 75 words a unique vacation rental inCheyenne, WY with the title \" Gorgeous Cottage Close to Capitol Let Us Spoil You \" including a detail about the amenities.",
    "text_stimuli (title)": "Gorgeous Cottage Close to Capitol Let Us Spoil You",
    "text_stimuli": "\"Gorgeous Cottage Close to Capitol - Let Us Spoil You\" is a luxurious retreat nestled in a quiet neighborhood just three blocks from Wyoming's State Capitol in Cheyenne. This beautifully restored 1920s cottage boasts modern amenities while retaining its historic charm. The highlight is a lavish spa-like bathroom featuring a deep soaking tub with chromotherapy lighting and a multi-jet shower system. Guests can unwind in the private courtyard garden or enjoy the gourmet kitchen equipped with top-of-the-line appliances and a complimentary wine selection.",
    "text_type": "AI",
    "text_word_count": 82,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: \"Gorgeous Cottage Close to Capitol - Let Us Spoil You\" is a luxurious retreat nestled in a quiet neighborhood just three blocks from Wyoming's State Capitol in Cheyenne. This beautifully restored 1920s cottage boasts modern amenities while retaining its historic charm. The highlight is a lavish spa-like bathroom featuring a deep soaking tub with chromotherapy lighting and a multi-jet shower system. Guests can unwind in the private courtyard garden or enjoy the gourmet kitchen equipped with top-of-the-line appliances and a complimentary wine selection.",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_cheyenne.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage  (General Fast -- Stable Diffusion XL)",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/20.S.W.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Grand Junction, CO",
    "text_prompt": "NA",
    "text_stimuli (title)": "Fruita/Loma Guest House at the Perfect Day Getaway",
    "text_stimuli": "This newly constructed \"Green\" home is a mix of modern and country styles and will surely inspire you to enjoy all of the outdoor activities the Grand Valley has to offer. The Perfect Day Getaway house is located on a quaint farm within 8 minutes of world-class hiking, mountain and road bicycling, and river rafting. It is a great launching point for day trips to Moab and the Grand Mesa as well! It was built to maximize the southern exposure and views of the Colorado National Monument.",
    "text_type": "Human",
    "text_word_count": 87,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_grandjunction.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/43.R.EA.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Casper, WY",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Casper, WY with the title \"ALMA Away\" including a detail about design.",
    "text_stimuli (title)": "ALMA Away",
    "text_stimuli": "A converted 1940s railway station turned modern retreat in Casper, Wyoming, featuring panoramic views of Casper Mountain. The property's most striking design element is its circular great room, housed in the former station's ticket rotunda, with original Art Deco terrazzo flooring. This three-bedroom hideaway seamlessly blends historical architecture with contemporary comfort, offering guests a unique railway-inspired experience. The space includes a gourmet kitchen, outdoor fire pit, and private garden where vintage railway memorabilia creates an authentic atmosphere throughout.",
    "text_type": "AI",
    "text_word_count": 78,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "Create an image of the outside, external front view of the described vacation rental listing:[\" ALMA Away showcases sophisticated mountain modern design with its clean architectural lines and natural materials throughout. The interior features a striking combination of reclaimed Wyoming barn wood, floor-to-ceiling windows, and contemporary steel accents. Custom-built furniture pieces and local artisan metalwork complement the home's minimalist aesthetic, while cozy touches like sheepskin throws and handwoven textiles create an inviting mountain retreat atmosphere.\"]",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_casper.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage  (General Fast -- Stable Diffusion XL)",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/35.S.EA.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Duluth, MN",
    "text_prompt": "NA",
    "text_stimuli (title)": "No cleaning fee - Boutique Guest Suite in Duluth",
    "text_stimuli": "Welcome to your sweet escape at Allendale Orchard in Duluth! A perfect oasis for a couple or solo traveler. Relax on your private deck or in the soaking tub after a day of exploring all that Duluth and the North Shore has to offer. You'll be close to an abundance of hiking and biking trails, minutes away from quaint coffee shops and award winning restaurants, and can pick your own seasonal fruit right on the property. We're here to offer all of our guests a personalized and inviting experience!",
    "text_type": "Human",
    "text_word_count": 89,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_duluth.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/2.R.SA.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Sun City, AZ",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Sun City, AZ with the title \"Luxury Modern Getaway\" including a detail design.",
    "text_stimuli (title)": "Luxury Modern Getaway",
    "text_stimuli": "A stunning desert oasis in Sun City, Arizona, showcasing minimalist architecture with floor-to-ceiling windows that frame spectacular sunset views. The home's signature design feature is a floating staircase crafted from glass and brushed steel, illuminated by a cascading LED chandelier. This four-bedroom sanctuary offers a resort-style pool, outdoor kitchen, and meditation garden. Smart home technology and custom Italian furnishings complete this sophisticated desert retreat, perfect for those seeking contemporary elegance in the heart of Arizona.",
    "text_type": "AI",
    "text_word_count": 75,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\" Luxury Modern Getaway showcases contemporary Southwest minimalism with its clean lines, soaring ceilings, and floor-to-ceiling windows that frame desert mountain views. The interior features a sophisticated neutral palette accented by geometric patterns and metallic finishes. Custom-built floating shelves, Italian porcelain tiles, and statement lighting fixtures create an upscale ambiance, while the open-concept living space flows seamlessly to the resort-style patio.\"]",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_suncity.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini (2.0 Flash)",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/33.S.SA.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Fort Worth, TX",
    "text_prompt": "NA",
    "text_stimuli (title)": "Cozy Casita in Alamo Heights!",
    "text_stimuli": "Centrally-located and newly renovated  bungalow built in 1943. Minutes from Dickies Arena, Amon Carter Stadium, TCU, Fort Worth Botanic Gardens, Sundance Square, Trinity Park, the Stockyards, and so much more! Great for couples, friends, and families who want to explore all that Fort Worth has to offer. Within walking distance of great restaurants and diners as well as a fully stocked kitchen. Long-term corporate renters are welcome! Please ask about discounted rates for extended stays.",
    "text_type": "Human",
    "text_word_count": 75,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_fortworth2.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/45.R.B.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Watertown,",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Independence, MO with the title \"Mayfair Drive\" including a detail about amenities.",
    "text_stimuli (title)": "Mayfair Drive",
    "text_stimuli": "A meticulously restored mid-century ranch home near historic Independence Square offers a blend of vintage charm and modern luxury. This three-bedroom retreat features original hardwood floors, designer furnishings, and a gourmet kitchen with professional-grade appliances. Guests enjoy a private backyard oasis with covered patio, fire pit, and herb garden. The master suite includes a spa-like bathroom with heated floors. A dedicated work space with high-speed fiber internet makes this home perfect for remote workers or extended stays.",
    "text_type": "AI",
    "text_word_count": 77,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: Mayfair Drive offers serene lodging in a remodeled mid-century ranch located in tranquil Independence. This thoughtfully updated home features premium amenities including a fully-equipped smart kitchen with a Keurig coffee station, high-speed fiber internet, and streaming services on all TVs. The spacious interior showcases modern farmhouse decor, while the fenced backyard includes a covered patio with gas grill and outdoor dining space.",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_watertown.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini (2.0 Flash)",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/24.S.SA.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Aberdeen, SD",
    "text_prompt": "NA",
    "text_stimuli (title)": "Lusso Cottage ñ Cozy and Comfortable!",
    "text_stimuli": "Welcome to Lusso Cottage! No detail was too small in this charming and cozy home. Enjoy the comfortable furnishings or a relaxing evening on the patio when weather permits. You can cozy up in front of the fireplace enjoying games, or the 65\" TV with Wi-Fi, Netflix and Amazon Prime. Minutes from Northern State University, Presentation College, Avera and Sanford hospitals and Story Book Land.",
    "text_type": "Human",
    "text_word_count": 65,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_aberdeen.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/33.R.SA.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Independence, MO",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Independence, MO with the title \"Cute & Cozy / Close to everything\" including a detail about a nearest tourist attraction.",
    "text_stimuli (title)": "Cute & Cozy / Close to everything",
    "text_stimuli": "Just two miles from the Harry S. Truman Home National Historic Site, this renovated 1940s bungalow offers the perfect base for exploring Independence's rich history. The two-bedroom home features an updated kitchen, comfortable living space with smart TV, and a cozy front porch perfect for morning coffee. Walking distance to the historic Independence Square, restaurants, and antique shops. Enjoy modern amenities in a historic setting, with easy access to Kansas City attractions.",
    "text_type": "AI",
    "text_word_count": 72,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\" Cute & Cozy / Close to everything is a charming 1950s bungalow located just a 5-minute drive from the Harry S. Truman Presidential Library and Museum. This freshly renovated home features retro-inspired decor, a bright open-concept living space, and a fully equipped kitchen with vintage touches. The peaceful backyard offers a covered patio with string lights, perfect for evening relaxation after exploring Independence's historic sites. \"]",
    "place_stimuli": "stimuli/AI/ai_places_assessment_24/ai_independence.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini (2.0 Flash)",
    "face_stimuli": "stimuli/AI/ai_faces_assessment_24/32.S.B.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Batavia, NY",
    "text_prompt": "NA",
    "text_stimuli (title)": "Wheatland Schoolhouse No.7",
    "text_stimuli": "Charming Country Schoolhouse Retreat: Step into history with modern comforts in our beautifully renovated 1800s schoolhouse. Nestled in a peaceful setting, this unique Airbnb offers two cozy bedrooms, each with a private bath. The open floor plan and spacious, fully equipped kitchen make it ideal for a relaxing long weekend escape. Enjoy the charm of the countryside with all the comforts of home. Perfect for families, friends, or a romantic getaway!",
    "text_type": "Human",
    "text_word_count": 71,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_assessment_24/human_batavia.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_assessment_24/21.R.W.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured"
  }
]