var intervention_stim_multifeatured = [
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "New Orleans, LO",
    "text_prompt": "NA",
    "text_stimuli (title)": "Algiers Point",
    "text_stimuli": "If you love vibrant architecture, then you'll love Algiers Point. It's the second oldest neighborhood in New Orleans, minutes away from the French Quarter. Algiers Point offers delicious food, local bars with live music and much chiller vibes. Our charming loft is a private suite and offers a full stack kitchen, access to a spacious gated courtyard, and sleeps 3 to 4 people. You'll have access to 2 Schwinn bikes you can ride along the river and an outdoor tub to cool down in when you return.",
    "text_type": "Human",
    "text_word_count": 87,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_neworleans.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/9.R.B.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "AL",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Miami, FL",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Miami, FL with the title Cozy studio with private garden including proximity to the Miami airport.",
    "text_stimuli (title)": "Charming Studio with Private Garden",
    "text_stimuli": "Located just 10 minutes from Miami International Airport, this cozy studio offers a peaceful retreat in the heart of the city. The stylish, open-plan space features a comfortable queen bed, a kitchenette, and a spacious bathroom. Outside, unwind in your own lush private garden, perfect for enjoying a quiet morning or a relaxing evening. Close to popular dining and attractions, it's the perfect blend of convenience and tranquility for couples or solo travelers.",
    "text_type": "AI",
    "text_word_count": 73,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\"\nCharming Studio with Private Garden:    \nLocated just 10 minutes from Miami International Airport, this cozy studio offers a peaceful retreat in the heart of the city. The stylish, open-plan space features a comfortable queen bed, a kitchenette, and a spacious bathroom. Outside, unwind in your own lush private garden, perfect for enjoying a quiet morning or a relaxing evening. Close to popular dining and attractions, it's the perfect blend of convenience and tranquility for couples or solo travelers.\"].",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_miami.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage (General Fast -- Stable Diffusion XL)",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/3.S.W.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Las Vegas, NV",
    "text_prompt": "NA",
    "text_stimuli (title)": "Twin Palms Las Vegas",
    "text_stimuli": "If you can pull yourself away from the amazing and tranquil views, this historic mid-century modern home is located less than 10 minutes from The Strip, Downtown, shopping, and restaurants. It boasts a spacious floor plan, a large outdoor living area, pool, & bbq area, perfect for making new memories with friends & family. Like golf? This home sits on an award-winning golf course. Walk to the club house for breakfast or lunch, or dare I suggest a Bloody Mary?",
    "text_type": "Human",
    "text_word_count": 82,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_lasvegas.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/23.R.EA.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": 0.3,
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "AL",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Simi Valley, CA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Simi Valley, CA with the title Secluded Simi Sensation including the Santa Monica Mountains.",
    "text_stimuli (title)": "Secluded Simi Sensation",
    "text_stimuli": "Tucked away at the base of the picturesque Santa Monica Mountains, this peaceful retreat in Simi Valley offers a perfect escape. The modern-rustic rental boasts a spacious open floor plan, a refreshing pool, and a scenic deck with breathtaking mountain views. Ideal for nature enthusiasts, explore nearby hiking trails or unwind by the fire pit under the stars. With cozy interiors and a fully equipped kitchen, it's a serene getaway for couples or small gatherings.",
    "text_type": "AI",
    "text_word_count": 75,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing:",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_simivalley.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage (General Fast -- Stable Diffusion XL)",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/4.S.B.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Phoenix, AZ",
    "text_prompt": "NA",
    "text_stimuli (title)": "Lux+History+Htd Pool/Spa Ctrl to Spring Training",
    "text_stimuli": "Built in 1928, yet remodeled and professionally decorated in 2022, this Spanish Colonial Revival masterpiece on an idyllic palm-lined avenue adjacent to Encanto Park is the ideal getaway. Stroll the surrounding storybook lanes, cool off in the private pool, soak in the hot tub, lounge by the fire pit, or sleep late in one of 3 luxuriously appointed king bedrooms, including a main floor primary with en-suite bath. 2-car off-street parking and super-fast wifi make this the ideal home base.",
    "text_type": "Human",
    "text_word_count": 80,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_phoenix.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/44.R.EA.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "AL/SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Philadelphia, PA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Philadelphia, PA with the title The Bainbridge Trinity including it being in Queen Village neighborhood",
    "text_stimuli (title)": "The Bainbridge Trinity",
    "text_stimuli": "Located in the heart of Philadelphia's historic Queen Village neighborhood, The Bainbridge Trinity offers a perfect blend of modern comfort and classic charm. This beautifully restored trinity-style home boasts three spiral-staircase levels, a welcoming living area, a fully equipped kitchen, and a peaceful private patio. Set amidst cobblestone streets and lively local dining, it's an ideal retreat for exploring the city's rich history and culture while enjoying the cozy elegance of this unique urban haven.",
    "text_type": "AI",
    "text_word_count": 75,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\"\nThe Bainbridge Trinity\nLocated in the heart of Philadelphia's historic Queen Village neighborhood, The Bainbridge Trinity offers a perfect blend of modern comfort and classic charm. This beautifully restored trinity-style home boasts three spiral-staircase levels, a welcoming living area, a fully equipped kitchen, and a peaceful private patio. Set amidst cobblestone streets and lively local dining, it's an ideal retreat for exploring the city's rich history and culture while enjoying the cozy elegance of this unique urban haven.\"].",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_philadelphia.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini (2.0 Flash)",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/6.S.SA.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "San Antonio, TX",
    "text_prompt": "NA",
    "text_stimuli (title)": "The Plumeria Retreat on the Lake",
    "text_stimuli": "This recently built 2-bedroom, 2-bath San Antonio vacation rental is the perfect home base for a relaxing retreat with family or friends! Nestled in Towne Lake Subdivision, this home features free EV L2 charging, 3 Smart TVs, a fully equipped kitchen & furnished deck. Sip your coffee from the deck & enjoy the lake and plumeria garden views. Spend your time hiking local trails before heading out for shopping/sightseeing. Please note: This property is on the 2nd floor & requires stairs to access",
    "text_type": "Human",
    "text_word_count": 80,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_sanantonio.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/7.R.SA.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "AL/SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "San Diego, CA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in San Diego, CA with the title Fresh, hip and cozy private North Park guest house including it being near the San Diego Zoo",
    "text_stimuli (title)": "Fresh, Hip, and Cozy Private North Park Guest House",
    "text_stimuli": "This stylish and modern guest house in San Diego's trendy North Park neighborhood provides a comfortable escape just a short drive from the San Diego Zoo. Featuring a cozy queen bed, a sleek kitchenette, a beautifully designed bathroom, and a private patio for unwinding, it's a perfect blend of charm and convenience. Surrounded by craft breweries, eclectic restaurants, lively boutique shops, and vibrant nightlife, this peaceful retreat offers the ideal base for exploring the city.",
    "text_type": "AI",
    "text_word_count": 72,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\"\nFresh, Hip, and Cozy Private North Park Guest House\nThis stylish and modern guest house in San Diego's trendy North Park neighborhood provides a comfortable escape just a short drive from the San Diego Zoo. Featuring a cozy queen bed, a sleek kitchenette, a beautifully designed bathroom, and a private patio for unwinding, it's a perfect blend of charm and convenience. Surrounded by craft breweries, eclectic restaurants, and boutique shops, this peaceful retreat offers the ideal base for exploring the city.\"].",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_sandiego.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini (2.0 Flash)",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/50.S.SA.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Dallas, TX",
    "text_prompt": "NA",
    "text_stimuli (title)": "New Build Luxury Property in the Heart of Dallas!",
    "text_stimuli": "Welcome to our ultra luxury property that is located in the heart of Dallas minutes from downtown and is a brand new build! We have furnished the property with high end furniture and finishes! The property is located in a prime area of Dallas and is 5 minutes away from American Airlines Center, Katy Trail, Deep Ellum, Downtown, and Uptown. We provide garage parking for your vehicle at no extra charge! We have also created an amazing, relaxing space on the rooftop deck that overlooks downtown!",
    "text_type": "Human",
    "text_word_count": 86,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_dallas.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/20.R.B.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "AL/SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "San Jose, CA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in San Jose, CA with the title Evergreen Valley Hillside retreat including its view over the city of San Jose",
    "text_stimuli (title)": "Evergreen Valley Hillside Retreat",
    "text_stimuli": "Perched in the scenic Evergreen Valley of San Jose, this stylish hillside getaway boasts breathtaking views of the city skyline and Santa Clara Valley. The retreat features expansive windows, a private balcony, and a tranquil patio complete with a firepit. With a fully-equipped kitchen, cozy living spaces, and elegant bedrooms, it's perfect for families or couples. Enjoy nearby hiking trails or relax as the sparkling city lights create an enchanting evening ambiance. A serene escape awaits!",
    "text_type": "AI",
    "text_word_count": 76,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\"\nEvergreen Valley Hillside Retreat\nPerched in the scenic Evergreen Valley of San Jose, this stylish hillside getaway boasts breathtaking views of the city skyline and Santa Clara Valley. The retreat features expansive windows, a private balcony, and a tranquil patio complete with a firepit. With a fully-equipped kitchen, cozy living spaces, and elegant bedrooms, it's perfect for families or couples. Enjoy nearby hiking trails or relax as the sparkling city lights create an enchanting evening ambiance. A serene escape awaits!\"].",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_sanjose.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini (2.0 Flash)",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/40.S.W.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Albuquerque, NM",
    "text_prompt": "NA",
    "text_stimuli (title)": "Mountain house 18 minutes from ABQ airport",
    "text_stimuli": "Desert Mountain Retreat is a contemporary southwestern home nestled in the foothills of the Sandia & Manzano Mountains. Recently renovated, Desert Mountain is at once modern yet traditional, reflecting the deep history of New Mexican architecture & style, with contemporary design elements. Our home is surrounded by mountains & high desert with plenty of space & hiking trails, yet only 18 minutes to the airport, 12 minutes to downtown, and 5 minutes to grocery stores & other services.",
    "text_type": "Human",
    "text_word_count": 73,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_albuquerque.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/43.R.B.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Colorado Springs, CO",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Colorado Springs, CO with the title Mountain View New Construction including being close to Pikes Peak",
    "text_stimuli (title)": "Mountain View New Construction",
    "text_stimuli": "Mountain View New Construction is a modern, stylish vacation rental nestled in the heart of Colorado Springs, offering breathtaking views of Pikes Peak. This newly built retreat boasts sleek interiors with an open-concept layout, a fully equipped kitchen, and cozy furnishings. Enjoy the spacious patio, perfect for sipping coffee or stargazing. Conveniently located near hiking trails, Garden of the Gods, and downtown attractions, it's an ideal base for exploring the wonders of the Rocky Mountains.",
    "text_type": "AI",
    "text_word_count": 75,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\"\nMountain View New Construction is a modern, stylish vacation rental nestled in the heart of Colorado Springs, offering breathtaking views of Pikes Peak. This newly built retreat boasts sleek interiors with an open-concept layout, a fully equipped kitchen, and cozy furnishings. Enjoy the spacious patio, perfect for sipping coffee or stargazing. Conveniently located near hiking trails, Garden of the Gods, and downtown attractions, it's an ideal base for exploring the wonders of the Rocky Mountains.\"].",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_coloradosprings.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage (General Fast -- Stable Diffusion XL)",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/15.S.W.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Omaha, NE",
    "text_prompt": "NA",
    "text_stimuli (title)": "Hot tub in beautiful backyard!",
    "text_stimuli": "Search no more! This cozy home has it all! Charming boho style, well equipped kitchen, comfy beds, plenty of space to relax in the 2 indoor living spaces.  But the BEST part of all is the inviting patio space with hot tub, plenty of seating & fire pit! Walking distance to downtown Benson with plentiful options for dining & nightlife. Another unique feature of this home is the dedicated workspace & workout room! This gem is truly your home away from home!",
    "text_type": "Human",
    "text_word_count": 79,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_omaha.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/1.R.EA.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Long Beach, CA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Long Beach, CA with the title Modern Beach House With A Backyard Oasis including its lemon trees",
    "text_stimuli (title)": "Modern Beach House With A Backyard Oasis",
    "text_stimuli": "Escape to a sleek, contemporary retreat in Long Beach, CA, just steps from the beach. This stylish 3-bedroom rental boasts an open-concept design with floor-to-ceiling windows, flooding the space with natural light. The private backyard is a true oasis, featuring vibrant lemon trees, a shaded pergola, a firepit, and a tranquil water feature. Perfect for families or couples, enjoy coastal charm blended with modern luxury, all within walking distance of shops, dining, and vibrant nightlife.",
    "text_type": "AI",
    "text_word_count": 75,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\"\nModern Beach House With A Backyard Oasis\n\nEscape to a sleek, contemporary retreat in Long Beach, CA, just steps from the beach. This stylish 3-bedroom rental boasts an open-concept design with floor-to-ceiling windows, flooding the space with natural light. The private backyard is a true oasis, featuring vibrant lemon trees, a shaded pergola, a firepit, and a tranquil water feature. Perfect for families or couples, enjoy coastal charm blended with modern luxury, all within walking distance of shops, dining, and vibrant nightlife.\"].",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_longbeach.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage (General Fast -- Stable Diffusion XL)",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/45.S.EA.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Virginia Beach, VA",
    "text_prompt": "NA",
    "text_stimuli (title)": "Paint The Beach Pink! Full House | Private Pool",
    "text_stimuli": "Take a break and unwind at your private pool! Stylish, updated interior and a spacious backyard with pool and lounge area. Rinse off at the outdoor shower after a day at the beach and enjoy your private retreat! The Rudee Inlet is less than a block away with great restaurants, fishing, and water activities. A path along the Rudee Inlet leads to the beach and shops - a quick 4 block trip with the included bikes! Outdoor seating and gas fire pit added for the cooler months!",
    "text_type": "Human",
    "text_word_count": 86,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_virginiabeach.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/14.R.B.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Oakland, CA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Oakland, CA with the title Luxury Travelers Retreat with Breathtaking Views including its French doors allowing open air",
    "text_stimuli (title)": "Luxury Travelers Retreat with Breathtaking Views",
    "text_stimuli": "Perched in the Oakland Hills, this elegant vacation rental offers sweeping views of the Bay Area skyline. French doors open wide to a private deck, inviting fresh air and California sunshine into the open-concept living space. Designer interiors, a spa-style bathroom, and gourmet kitchen create a luxurious home away from home. Perfect for couples or solo travelers seeking tranquility, style, and proximity to San Francisco and vibrant Oakland culture.",
    "text_type": "AI",
    "text_word_count": 73,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\"\nLuxury Travelers Retreat with Breathtaking Views\n\nExperience Oakland's finest in this chic vacation rental featuring stunning panoramic views of the Bay Area. French doors open onto a spacious deck, blending indoor elegance with outdoor serenity. This retreat boasts a sleek, modern design, a gourmet kitchen, and a cozy fireplace. Unwind in the soaking tub or sip wine al fresco under string lights. Located near vibrant restaurants and hiking trails, it's a perfect haven for luxury and adventure seekers alike.\"].\n\nCreate an image of the exterior view of the described vacation rental listing: [\"\nLuxury Travelers Retreat with Breathtaking Views\n\nExperience Oakland's finest in this chic vacation rental featuring stunning panoramic views of the Bay Area. French doors open onto a spacious deck, blending indoor elegance with outdoor serenity. This retreat boasts a sleek, modern design, a gourmet kitchen, and a cozy fireplace. Unwind in the soaking tub or sip wine al fresco under string lights. Located near vibrant restaurants and hiking trails, it's a perfect haven for luxury and adventure seekers alike.\"].",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_oakland.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage (General Fast -- Stable Diffusion XL)",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/19.S.EA.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Pittsburgh, PA",
    "text_prompt": "NA",
    "text_stimuli (title)": "Seneca Place: A historic home in Mount Lebanon.",
    "text_stimuli": "Seneca Place is a historic home. Our guests have the best of both worlds: a private full residence with attentive and available hosts (right next door). Please note that we charge by guest for requests over two, so please enter the correct number of guests to fully understand your costs.\nThis neighborhood is very quiet with little to no traffic and the hosts are ten feet away. There is a covered side patio with an outdoor sofa as well as a connecting back patio with a fire pit.",
    "text_type": "Human",
    "text_word_count": 88,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_pittsburgh.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/20.R.W.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Orlando, FL",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Orlando, FL with the title Modern Private Studio including recently renovated 1950s studio",
    "text_stimuli (title)": "Modern Private Studio",
    "text_stimuli": "This recently renovated 1950s studio apartment combines vintage charm with contemporary comfort in Orlando's trendy Colonialtown neighborhood. The space features sleek modern finishes, including a custom Murphy bed, quartz countertops, and designer lighting. The efficient layout maximizes every inch, offering a fully equipped kitchenette and stylish bathroom with rainfall shower. A private patio provides the perfect spot for morning coffee. Just minutes from downtown Orlando, Lake Eola Park, and popular Mills 50 district restaurants. Easy access to I-4 and twenty minutes to theme parks.",
    "text_type": "AI",
    "text_word_count": 84,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing:\n\nThis recently renovated 1950s studio apartment combines vintage charm with contemporary comfort in Orlando's trendy Colonialtown neighborhood. The space features sleek modern finishes, including a custom Murphy bed, quartz countertops, and designer lighting. The efficient layout maximizes every inch, offering a fully equipped kitchenette and stylish bathroom with rainfall shower. A private patio provides the perfect spot for morning coffee. Just minutes from downtown Orlando, Lake Eola Park, and popular Mills 50 district restaurants. Easy access to I-4 and twenty minutes to theme parks.",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_orlando.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini (2.0 Flash)",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/45.S.W.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Costa Mesa, CA",
    "text_prompt": "NA",
    "text_stimuli (title)": "Eastside Casita",
    "text_stimuli": "Located 1/2 mile from Newport Beach and walking distance to a variety of restaurants, cafes, bars, and stores it is great home base for exploring the Newport Beach and Costa Mesa area and is just 2 miles from the water! Guest house is detached from main house, has private entrance, parking, full kitchen and fenced off back yard space. The Patio includes a BBQ and patio table to enjoy So-Cal evenings or take in the sun while not out exploring. Accommodating for both adventure and work travel!",
    "text_type": "Human",
    "text_word_count": 87,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_costamesa.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/5.R.SA.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Newark, NJ",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Newark, NJ with the title Modern City Getaway Near Downtown Newark, NYC, EWR including its proximity to the Red Bull Arena",
    "text_stimuli (title)": "Modern City Getaway Near Downtown Newark, NYC, EWR",
    "text_stimuli": "This stylish and cozy vacation rental offers a contemporary urban retreat just minutes from downtown Newark, NYC access, and Newark Airport (EWR). Enjoy a fully equipped kitchen, high-speed Wi-Fi, and a comfortable lounge area with city views. Located 10 minutes from Red Bull Arena, it's perfect for sports fans and concertgoers. Explore the vibrant Ironbound District and its renowned dining scene, or take a quick train ride to Manhattan. Ideal for modern travelers!",
    "text_type": "AI",
    "text_word_count": 73,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: [\"\nModern City Getaway Near Downtown Newark, NYC, EWR\nThis stylish and cozy vacation rental offers a contemporary urban retreat just minutes from downtown Newark, NYC access, and Newark Airport (EWR). Enjoy a fully equipped kitchen, high-speed Wi-Fi, and a comfortable lounge area with city views. Located 10 minutes from Red Bull Arena, it's perfect for sports fans and concertgoers. Explore the vibrant Ironbound District and its renowned dining scene, or take a quick train ride to Manhattan. Ideal for modern travelers!\"].",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_newark.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini (2.0 Flash)",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/30.S.SA.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Irving, TX",
    "text_prompt": "NA",
    "text_stimuli (title)": "Cozy 3 Bed 2.5 Bath entire home near DFW Airport",
    "text_stimuli": "Welcome to your ideal retreat! This 3-bedroom home features a king bed with an en-suite bathroom, a queen bed with a full bathroom, and a third queen bed with a half bathroom. This home also features a smart TV in every bedroom! Blowup queen mattress is available too to fit 7 if needed. Enjoy the entire house and a large, pet-friendly backyard\u2014great for your furry friends. Relax on the outdoor patio with a table and a charcoal grill. Fast Wi-Fi supports work-from-home needs.",
    "text_type": "Human",
    "text_word_count": 83,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_irving.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/13.R.W.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Rochester, NY",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Rochester, NY with the title \"Cozy bungalow in desirable area!\" including a factor about the neighborhood.",
    "text_stimuli (title)": "Cozy bungalow in desirable area!",
    "text_stimuli": "Located in Rochester's sought-after Park Avenue neighborhood, known for its tree-lined streets and historic architecture, this charming 1930s bungalow offers a perfect city retreat. The two-bedroom home features a welcoming front porch, updated kitchen with breakfast nook, and original hardwood floors throughout. Just steps from the area's celebrated cafes, boutiques, and the annual Park Ave Festival. Minutes from the Memorial Art Gallery, George Eastman Museum, and Highland Park's famous lilac gardens. Easy access to University of Rochester and Strong Memorial Hospital.",
    "text_type": "AI",
    "text_word_count": 81,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: Located in Rochester's sought-after Park Avenue neighborhood, known for its tree-lined streets and historic architecture, this charming 1930s bungalow offers a perfect city retreat. The two-bedroom home features a welcoming front porch, updated kitchen with breakfast nook, and original hardwood floors throughout. Just steps from the area's celebrated cafes, boutiques, and the annual Park Ave Festival. Minutes from the Memorial Art Gallery, George Eastman Museum, and Highland Park's famous lilac gardens. Easy access to University of Rochester and Strong Memorial Hospital.",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_rochester.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/36.S.SA.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": 0.4,
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Spokane Valley, WA",
    "text_prompt": "NA",
    "text_stimuli (title)": "Huge Home, Pool Table, Hot Tub",
    "text_stimuli": "Located in a prestigious neighborhood, this fully updated home boasts 4000 sq. ft. of living space, comfortably accommodating 16. Unwind and de-stress with the hot tub, 4 smart TV's, fire pit, and city views. Enjoy a game of pool, foosball, or a round on the Pac-Man arcade. A home gym & nearby trails await the active enthusiast. Loaded to the max with amenities this escape offers the perfect blend of entertainment and comfort.",
    "text_type": "Human",
    "text_word_count": 72,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_spokanevalley.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/16.R.SA.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": 1.2,
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "San Bernardino, CA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in San Bernardino, CA with the title \" Downtown Redlands Historic Wonderland \" including a detail about the location.",
    "text_stimuli (title)": "Downtown Redlands Historic Wonderland",
    "text_stimuli": "Nestled in the heart of historic Redlands, just two blocks from the iconic Redlands Bowl amphitheater, this restored 1920s Craftsman bungalow exudes California charm. The three-bedroom home features period details, including built-in cabinets and original windows, alongside modern amenities. A wraparound porch and citrus-filled backyard offer perfect spots to enjoy the year-round Mediterranean climate. Walking distance to State Street's boutiques, cafes, and the historic A.K. Smiley Public Library. Easy access to mountain trails and San Bernardino National Forest.",
    "text_type": "AI",
    "text_word_count": 78,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: Downtown Redlands Historic Wonderland nestles in the heart of Redlands' historic district, mere steps from the celebrated Fox Theater and vibrant State Street corridor. This meticulously maintained 1920s Craftsman showcases period charm while offering modern comfort. Located in a tree-lined neighborhood, guests can stroll to artisanal coffee shops, boutique shopping, and the popular farmers' market, yet enjoy serene surroundings in this historic enclave.",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_sanbernardino.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/7.S.EA.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": 99.9,
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Muncie, IN",
    "text_prompt": "NA",
    "text_stimuli (title)": "Quaint carriage house.",
    "text_stimuli": "You'll think you are in the country when you arrive at our peaceful 10 acre property right in Muncie. Located near our historic home, built in 1848, you'll find a carriage house with an upstairs apartment with everything you need for a relaxing and comfortable stay. This is a quaint, rustic cabin like space with private outdoor area. You are only five to 10 minutes from BSU and IU Ball Hospital, downtown, Elm Street Brewing, the Children's Museum, walking trails and most restaurants.",
    "text_type": "Human",
    "text_word_count": 83,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_muncie.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/46.R.W.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Florence, SC",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Florence, SC with the title \" Hadley's Hideaway \" including a detail about the location.",
    "text_stimuli (title)": "Hadley's Hideaway",
    "text_stimuli": "Situated in Florence's historic district, just three blocks from the Francis Marion University Performing Arts Center, this renovated 1940s cottage offers southern charm with modern comfort. The two-bedroom home features original hardwood floors, a screened-in porch with rocking chairs, and a bright, updated kitchen. The peaceful backyard garden provides a tranquil setting for morning coffee or evening relaxation. Walking distance to downtown restaurants, the Florence County Museum, and the weekly farmers market. Minutes from Florence Regional Airport and Interstate 95 access.",
    "text_type": "AI",
    "text_word_count": 81,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: Situated in Florence's historic district, just three blocks from the Francis Marion University Performing Arts Center, this renovated 1940s cottage offers southern charm with modern comfort. The two-bedroom home features original hardwood floors, a screened-in porch with rocking chairs, and a bright, updated kitchen. The peaceful backyard garden provides a tranquil setting for morning coffee or evening relaxation. Walking distance to downtown restaurants, the Florence County Museum, and the weekly farmers market. Minutes from Florence Regional Airport and Interstate 95 access.",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_florence.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/38.S.B.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": 0,
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Concord, NH",
    "text_prompt": "NA",
    "text_stimuli (title)": "Historic Colonial Downtown, Room #1",
    "text_stimuli": "Enjoy Downtown Concord without breaking the bank! Step into New England history at this Colonial built in 1855, while still enjoying modern amenities and the comforts of home. First floor of the house is owner-occupied and locked off from guests. The second floor has a separate entrance, shared bathroom, storage, and three locking bedrooms rented individually. This listing, Room #1, is the largest room and includes a queen bed, desk, closet, mini-fridge, microwave, WiFi, heat/AC, TV, and more.",
    "text_type": "Human",
    "text_word_count": 78,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_concord.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/24.R.EA.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": 1.7,
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Daytona Beach, FL",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Daytona Beach, FL with the title \" Glorious Oceanfront Escape: 1BR Private Balcony \" including a detail about the location.",
    "text_stimuli (title)": "Glorious Oceanfront Escape: 1BR Private Balcony",
    "text_stimuli": "Perched on the 12th floor of an exclusive beachfront complex, just steps from the Daytona Beach Pier and Boardwalk, this modern condo offers breathtaking ocean views from every room. The stylish one-bedroom unit features floor-to-ceiling windows, a fully equipped kitchen, and a private balcony perfect for watching sunrise over the Atlantic. Building amenities include two oceanfront pools and secured parking. Located minutes from Daytona International Speedway, Ocean Walk Shoppes, and popular beach restaurants. Direct beach access with complimentary chairs and umbrellas for guests.",
    "text_type": "AI",
    "text_word_count": 83,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "Create an image of the front view of the described vacation rental listing:  Perched on the 12th floor of an exclusive beachfront complex, just steps from the Daytona Beach Pier and Boardwalk, this modern condo offers breathtaking ocean views from every room. The stylish one-bedroom unit features floor-to-ceiling windows, a fully equipped kitchen, and a private balcony perfect for watching sunrise over the Atlantic. Building amenities include two oceanfront pools and secured parking. Located minutes from Daytona International Speedway, Ocean Walk Shoppes, and popular beach restaurants. Direct beach access with complimentary chairs and umbrellas for guests.",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_daytonabeach.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/12.S.SA.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": 0.1,
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Billings, MT",
    "text_prompt": "NA",
    "text_stimuli (title)": "Industrial Loft@Old Pine Retreat",
    "text_stimuli": "Here is your opportunity to experience a remote getaway just minutes away from downtown Billings. This beautiful, vintage-industrial themed house has features that include a 21 foot high ceiling in the living room, a gas fireplace, a loft master bedroom and a second bedroom, large bathrooms on both levels and a private deck. If this isn't enough, the views and remote space that you will get to experience will be enough to take your breath away!",
    "text_type": "Human",
    "text_word_count": 76,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_billings1.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/33.R.EA.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Charleston, SC",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Charleston, SC with the title \" Stunning Couples Cottage with Creek Dock! \" including a detail about the location.",
    "text_stimuli (title)": "Stunning Couples Cottage with Creek Dock!",
    "text_stimuli": "Positioned on tranquil Shem Creek in Mount Pleasant's coveted Old Village district, this enchanting 600-square-foot hideaway delivers waterfront peace just minutes from Charleston's historic center. The expertly updated cottage includes a personal dock ideal for paddling adventures and wildlife viewing, plus a breezy screened veranda overlooking the water. Situated moments from fresh seafood dining and the historic Pitt Street Bridge, this intimate escape merges coastal allure with contemporary comfort.",
    "text_type": "AI",
    "text_word_count": 78,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "Create an image of the exterior view of the described vacation rental listing: \"Stunning Couples Cottage with Creek Dock!\"\n\nPositioned on tranquil Shem Creek in Mount Pleasant's coveted Old Village district, this enchanting 600-square-foot hideaway delivers waterfront peace just minutes from Charleston's historic center. The expertly updated cottage includes a personal dock ideal for paddling adventures and wildlife viewing, plus a breezy screened veranda overlooking the water. Situated moments from fresh seafood dining and the historic Pitt Street Bridge, this intimate escape merges coastal allure with contemporary comfort.",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_charleston1.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/35.S.B.F.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": 0,
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Rockford, IL",
    "text_prompt": "NA",
    "text_stimuli (title)": "Relaxing Riverside Stay w HotTub",
    "text_stimuli": "Welcome to our thoughtfully designed River Home on a safe, quiet, private drive on the highly desired Rock River. Get ready to enjoy indoor-outdoor living at its finest. This pet and family-friendly space features a 6-person hot tub, furnished riverfront deck, game room w/ pool and darts, fire pit, and an ensuite-covered second-floor patio. Although this home is secluded, you're only 10 minutes from Anderson Japanese Gardens, SportsCore 1, and multiple fine dining options in downtown Rockford.",
    "text_type": "Human",
    "text_word_count": 77,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_rockford.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/24.R.SA.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Appleton, WI",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Appleton, WI with the title \"Sweet Getaway\" including a detail about a nearest tourist attraction.",
    "text_stimuli (title)": "Sweet Getaway",
    "text_stimuli": "Located just a mile from the famous Hearthstone Historic House Museum, this charming craftsman bungalow offers a cozy retreat in Appleton's historic district. The two-bedroom home features a welcoming living room with a gas fireplace, updated kitchen with local coffee service, and a peaceful sunroom overlooking the garden. The covered back patio provides a perfect spot for enjoying Wisconsin's summer evenings. Easy walking distance to Lawrence University, the Fox River Trail, and downtown's diverse dining scene.",
    "text_type": "AI",
    "text_word_count": 61,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "Create an image of the outside, external front view of the described vacation rental listing: [\" Sweet Getaway is a delightful two-story Victorian home situated just a 5-minute walk from the Fox Cities Performing Arts Center. This elegantly restored 1890s residence features period details, including ornate woodwork and stained glass windows. The cozy interior combines vintage charm with modern comfort, offering a gourmet kitchen, three bedrooms with plush bedding, and a wraparound porch perfect for morning coffee.\"]",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_appleton.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage  (General Fast -- Stable Diffusion XL)",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/20.S.B.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "La Crosse, WI",
    "text_prompt": "NA",
    "text_stimuli (title)": "Northshore Cottage (2 bedrooms) on Lake Onalaska",
    "text_stimuli": "Come stay at our cozy and comfortable two bedroom cottage located in a quiet neighborhood with views and access to Lake Onalaska. Walk across the street to hiking/biking trails. Near the Great River State Bike Trail. The Lake Onalaska canoe/kayak trail goes past our shoreline. Two sit on top kayaks and two easy ride bicycles are included. There are fishing boat rentals nearby or you can fish from the shore while enjoying Lake Onalaska's famous sunsets. No cleaning fee!",
    "text_type": "Human",
    "text_word_count": 79,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_lacrosse.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/41.R.EA.M.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Vincennes, IN",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Vincennes, IN with the title \"Cozy Two Bedroom Home\" including a detail about a nearest tourist attraction.",
    "text_stimuli (title)": "Cozy Two Bedroom Home",
    "text_stimuli": "Located just five minutes from the historic George Rogers Clark National Historical Park, this charming brick home offers a comfortable stay in Indiana's oldest city. The newly updated property features a welcoming living room with original hardwood floors, a fully equipped kitchen, and a covered front porch perfect for morning coffee. Period details blend seamlessly with modern conveniences throughout this historic district gem. Guests can easily walk to Vincennes University campus, the Indiana Military Museum, and downtown's vibrant restaurant scene.",
    "text_type": "AI",
    "text_word_count": 80,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: Located just five minutes from the historic George Rogers Clark National Historical Park, this charming brick home offers a comfortable stay in Indiana's oldest city. The newly updated property features a welcoming living room with original hardwood floors, a fully equipped kitchen, and a covered front porch perfect for morning coffee. Period details blend seamlessly with modern conveniences throughout this historic district gem. Guests can easily walk to Vincennes University campus, the Indiana Military Museum, and downtown's vibrant restaurant scene.",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_vincennes.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage  (General Fast -- Stable Diffusion XL)",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/42.S.EA.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Twin Falls, ID",
    "text_prompt": "NA",
    "text_stimuli (title)": "Deluxe Retreat! Hot tub, sauna, and canyon views!",
    "text_stimuli": "This beautifully remodeled duplex is situated on 1.5 acres at the edge of Rock Creek Canyon. Enjoy spanning countryside and canyon views while being only 7 mins away from Twin Falls' wide variety of shopping and restaurants. Kick back, relax and take in the views from the hot tub or sauna. Come stay in style and enjoy all the adventures in Twin Falls.",
    "text_type": "Human",
    "text_word_count": 63,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_twinfalls.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/9.R.W.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Watertown, SD",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Watertown, SD with the title \"Mayfair Drive\" including a detail about amenities.",
    "text_stimuli (title)": "Mayfair Drive",
    "text_stimuli": "Experience South Dakota charm in this completely renovated 1950s ranch home, situated in Watertown's peaceful east side neighborhood. This three-bedroom retreat features mid-century modern furnishings and an open-concept living space perfect for family gatherings. The gourmet kitchen boasts stainless steel appliances and a coffee bar with local roasts. Amenities include smart home features, high-speed fiber internet, and a spacious backyard patio with a gas grill and fire pit for evening entertainment and stargazing. Just minutes from Lake Kampeska and downtown shopping.",
    "text_type": "AI",
    "text_word_count": 81,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "Create an image of the front view of the described vacation rental listing: Experience South Dakota charm in this completely renovated 1950s ranch home, situated in Watertown's peaceful east side neighborhood. This three-bedroom retreat features mid-century modern furnishings and an open-concept living space perfect for family gatherings. The gourmet kitchen boasts stainless steel appliances and a coffee bar with local roasts. Amenities include smart home features, high-speed fiber internet, and a spacious backyard patio with a gas grill and fire pit for evening entertainment and stargazing. Just minutes from Lake Kampeska and downtown shopping.",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_watertown.jpg",
    "place_type": "AI",
    "gAI_system_places": "Mage  (General Fast -- Stable Diffusion XL)",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/1.S.B.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Bentonville, AR",
    "text_prompt": "NA",
    "text_stimuli (title)": "The Overlook",
    "text_stimuli": "Prime location in downtown Bentonville and hosts that are clean freaks! You will be extra comfortable in our stylish space with huge windows and sleek modern interior. Hop on the bike trails, walk to the museums and stroll to all the downtown bars and restaurants. Two single speed cruiser bikes with locks are included with your stay.  With our hands-on approach to guest satisfaction and extra touches, your comfort is our top priority.",
    "text_type": "Human",
    "text_word_count": 73,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_bentonville.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/16.R.SA.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Jackson, WY",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Jackson, WY with the title \"Cozy Mountain Escape in Jackson\" including a detail about the location.",
    "text_stimuli (title)": "Cozy Mountain Escape in Jackson",
    "text_stimuli": "Nestled in the heart of Jackson's historic district, just three blocks from Town Square and its iconic antler arches, this renovated log cabin offers authentic Wyoming charm. The one-bedroom retreat features panoramic Teton views, a stone fireplace, and rustic-modern decor. After a day of skiing at Jackson Hole Resort (15 minutes away), unwind in the private outdoor hot tub. The property includes a fully equipped gourmet kitchen, complimentary snowshoes, and easy access to local hiking trails and the National Elk Refuge.",
    "text_type": "AI",
    "text_word_count": 81,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "Create an image of the exterior front view of the described vacation rental listing: [\" Cozy Mountain Escape in Jackson is perfectly situated just 10 minutes from Jackson Hole Mountain Resort and five minutes from the historic Town Square. This charming mountain retreat offers breathtaking views of the Teton Range from its wraparound deck. The interior features rustic-luxe design with reclaimed timber accents, while large picture windows frame the surrounding mountain landscape and abundant wildlife.\"]",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_jackson.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini (2.0 Flash)",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/8.S.B.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Glens Falls, NY",
    "text_prompt": "NA",
    "text_stimuli (title)": "The Dax",
    "text_stimuli": "Nestled along the foothills of the gorgeous Adirondack mountains, you will find this unique & modern gambrel-style cabin the perfect getaway. With modern amenities along with plenty of extras, you can be as busy or as low-key as you would like. You will find locally-sourced items with intentional & personalized touches throughout the space to ensure your stay will feel like home. Located at an equal distance of 25 minutes to both Saratoga Springs, NY & Lake George, NY ...adventure awaits!",
    "text_type": "Human",
    "text_word_count": 78,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/Human/human_places_intervention_20/human_glenfalls.jpg",
    "place_type": "Human",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/Human/human_faces_intervention_20/42.R.EA.F.png",
    "face_type": "Human",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "multifeatured",
    "watermark": "stimuli/human_watermark.png"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Richmond, IN",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Richmond, IN with the title \"The Cottage on Abington Pike - Earlham College\" including a detail about amenities.",
    "text_stimuli (title)": "The Cottage on Abington Pike - Earlham College",
    "text_stimuli": "This charming 1920s craftsman cottage sits just minutes from Earlham College's campus, offering a peaceful retreat for visiting families and faculty. The newly renovated 2-bedroom home features original hardwood floors, a wraparound porch perfect for morning coffee, and a cozy gas fireplace. Modern amenities include a fully equipped smart kitchen with a Nespresso machine, high-speed WiFi, and a dedicated workspace. The fenced backyard provides a serene garden setting with a charming pergola and herb garden.",
    "text_type": "AI",
    "text_word_count": 65,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "Create an image of the exterior front view of the described vacation rental listing: [\" The Cottage on Abington Pike - Earlham College is a charming renovated farmhouse just minutes from campus. This cozy retreat features modern amenities including a fully-equipped kitchen with Keurig coffee station, high-speed fiber internet, and smart home technology throughout. The comfortable living space offers a 55\" smart TV with streaming services, while the peaceful screened porch overlooks a private garden with bird feeders and native plantings. \"]",
    "place_stimuli": "stimuli/AI/ai_places_intervention_20/ai_richmond.jpg",
    "place_type": "AI",
    "gAI_system_places": "Gemini (2.0 Flash)",
    "face_stimuli": "stimuli/AI/ai_faces_intervention_20/23.S.W.M.png",
    "face_type": "AI",
    "gAI_system_faces": "StyleGAN2",
    "ai_score": "",
    "listing_type": "AI",
    "features": "multifeatured",
    "watermark": "stimuli/ai_watermark.png"
  }
]