var intervention_stim_text = [
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Louisville, Kentucky",
    "text_prompt": "NA",
    "text_stimuli (title)": "Edward Tyler House",
    "text_stimuli": "Historic, unique, tasteful and serene - the Edward Tyler house, ca. 1783, is a stone cabin 20 minutes SE of Louisville on 13 acre estate. Near the famous bourbon trail, rental includes full cabin and large screen porch overlooking pond with fountain. First floor has living/dining/kitchen space with small sofa bed and stone fireplace (gas); queen bed and full bath on second floor. American and European antique furnishings and fine art welcome you to fully updated home with central HVAC.",
    "text_type": "Human",
    "text_word_count": 79,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "AL",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Broken Arrow, OK",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Broken Arrow, OK with the title Rose District's Lofted Tiny Home including its proximity to the Rose District.",
    "text_stimuli (title)": "Rose District's Lofted Tiny Home",
    "text_stimuli": "Situated steps from Broken Arrow's lively Rose District, this cozy lofted tiny home offers a perfect retreat. Just a 2-minute stroll to Main Street, guests can explore boutique shops, trendy restaurants, and local events. The thoughtfully designed space features modern amenities, a snug loft bedroom, and a charming patio for relaxation. Perfect for couples or solo adventurers, this unique rental combines comfort and convenience in the heart of Broken Arrow's most vibrant area.",
    "text_type": "AI",
    "text_word_count": 73,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Indianapolis, Indiana",
    "text_prompt": "NA",
    "text_stimuli (title)": "Home in Indianapolis",
    "text_stimuli": "Cozy 2 bedroom, 1 bathroom home near all that downtown Indy has to offer! Located minutes from Lucas Oil, Gainbridge Fieldhouse, and the Indianapolis Convention Center. This home is also a short walk from the popular Fountain Square neighborhood. There is also an Ice cream shop directly across the Street! Free Street Parking, as well as a parking spot available on the property.",
    "text_type": "Human",
    "text_word_count": 63,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "AL",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Raleigh, NC",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Raleigh, NC with the title Creekside Hideaway - Hot Tub, 10 min to downtown including its location in secluded woods.",
    "text_stimuli (title)": "Creekside Hideaway - Hot Tub, 10 Min to Downtown",
    "text_stimuli": "Tucked away in a tranquil wooded area of Raleigh, Creekside Hideaway provides the perfect blend of nature and convenience, just 10 minutes from downtown. This stylish retreat features a fully equipped kitchen, cozy living spaces, and comfortable bedrooms. Relax on the deck overlooking the serene forest or enjoy the private hot tub under the night sky. With a charming creek nearby, it's an ideal getaway for couples or small groups seeking relaxation and easy city access.",
    "text_type": "AI",
    "text_word_count": 76,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Sunnyvale, CA",
    "text_prompt": "NA",
    "text_stimuli (title)": "Convenient, comfortable bed and bath in Sunnyvale!",
    "text_stimuli": "Our home, located in the heart of Silicon Valley, close to the Apple Spaceship, Stanford University, and Rancho San Antonio Park, provides a comfortable retreat from a busy travel/work day. Our neighborhood is quiet, friendly, and convenient to parks, schools, and two small shopping centers with a Starbucks, Zanotto's market/deli, and several local restaurants. We are excited to open our home to visitors from around the world. As we cook and bake frequently , homemade treats may be on offer!",
    "text_type": "Human",
    "text_word_count": 80,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "AL",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Fayetteville, NC",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Fayetteville, NC with the title R&S Guesthouse #2 Fayetteville/Fort Liberty including its closeness to the Segra Stadium",
    "text_stimuli (title)": "R&S Guesthouse #2 Fayetteville/Fort Liberty",
    "text_stimuli": "Discover comfort at R&S Guesthouse #2, a stylish two-bedroom haven located just 10 minutes from Segra Stadium. Perfect for sports enthusiasts or Fort Liberty visitors, this rental features a fully equipped kitchen, cozy furnishings, and a private patio to unwind. Enjoy free Wi-Fi, streaming options, and a peaceful setting in a charming neighborhood. Close to downtown Fayetteville, you'll have easy access to dining, shopping, entertainment, and local attractions. Perfect for both leisure and business travelers seeking convenience and ultimate relaxation!",
    "text_type": "AI",
    "text_word_count": 80,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Austin, TX",
    "text_prompt": "NA",
    "text_stimuli (title)": "Chic, Quiet + Central - Washington Cottage!",
    "text_stimuli": "Enjoy a stylish experience at this centrally-located cottage in a quiet little neighborhood! 5m to SoCo attractions, 3m to incredible food choices, 2m to St. Davids Hospital, and 4m from grocery. Bespoke and grand open living, dining, and kitchen spaces lead to two charming bedrooms each with its own gorgeous bathroom! A backyard fire pit and sitting area with some Austin charm! You will not regret your visit to this little bit of heaven!",
    "text_type": "Human",
    "text_word_count": 74,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "AL/SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Jacksonville, FL",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Jacksonville, FL with the title Studio styled barn on a Florida pecan farm including its pecan orchard",
    "text_stimuli (title)": "Studio-Styled Barn on a Florida Pecan Farm",
    "text_stimuli": "Experience a tranquil getaway at this cozy, studio-style barn set on a picturesque pecan farm near Jacksonville, FL. Combining rustic charm with modern amenities, the space includes a full kitchen, king-sized bed, and a private deck with stunning orchard views. Stroll through the pecan trees, enjoy fresh farm pecans, and soak in the serene surroundings. Conveniently located near Jacksonville's beaches and attractions, this unique retreat offers the perfect blend of comfort and countryside relaxation.",
    "text_type": "AI",
    "text_word_count": 74,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Fort Worth, TX",
    "text_prompt": "NA",
    "text_stimuli (title)": "Bluebonnet House - \"Discounted\" Stay, Close to TCU",
    "text_stimuli": "Welcome to the Bluebonnet House!\nThis cute house was lovingly remodeled in 2023, is located 1.1 miles from TCU, and is very close to other great Fort Worth attractions such as the Fort Worth Zoo, Botanic Gardens, the Museum District, and Sundance Square. You will feel right at home in our 1950s 2 bedroom, 1 and a half bathroom house with modern amenities. The open concept is perfect for small groups of family and friends. At night sit, outside on the spacious patio and enjoy the fire pit.",
    "text_type": "Human",
    "text_word_count": 88,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "AL/SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Columbus, OH",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Columbus, OH with the title Grandview Post-War Charmer including its proximity to Ohio State University",
    "text_stimuli (title)": "Grandview Post-War Charmer",
    "text_stimuli": "Discover this cozy, mid-century post-war gem nestled in Grandview Heights, just 10 minutes from Ohio State University. This charming 2-bedroom rental blends vintage flair with modern amenities, featuring original hardwood floors, a retro kitchenette, and a private garden patio. Walk to vibrant shops, restaurants, and breweries, or enjoy quiet evenings in the cozy living room. Perfect for Buckeye fans, families, or professionals, it offers a unique blend of comfort, history, local charm, and unbeatable convenience.",
    "text_type": "AI",
    "text_word_count": 72,
    "gAI_system_texts": "ChatGPT",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Minneapolis, MN",
    "text_prompt": "NA",
    "text_stimuli (title)": "Solar-Modern-Historic Suite, by Walker Art Center.",
    "text_stimuli": "Charmingly historic, quiet, residential neighborhood. The private, fully solar powered guest suite brings a modern aesthetic into a historic setting. Light-filled, spacious attic suite offers the feel of home. Enjoy the sun rise from the bedroom window, relax in the living room or stroll the quite streets around the lakes. We take the health and safety of our guests very seriously. We do our best for the utmost thorough cleaning.",
    "text_type": "Human",
    "text_word_count": 70,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Tulsa, OK",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Tulsa, OK with the title Downtown Delight including its proximity to Tulsa Performing Arts Center",
    "text_stimuli (title)": "Downtown Delight - A Stylish Tulsa Getaway",
    "text_stimuli": "Located just a 5-minute walk from the Tulsa Performing Arts Center, Downtown Delight offers a chic and comfortable urban retreat. This modern, loft-style rental boasts vibrant decor, an open-concept living space, and floor-to-ceiling windows with cityscape views. Guests will enjoy amenities like a fully equipped kitchen, a cozy reading nook, and a private balcony. Perfect for arts enthusiasts, it's nestled amidst trendy eateries and lively cultural spots, making it an ideal home base for exploring Tulsa.",
    "text_type": "AI",
    "text_word_count": 76,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Arlington, TX",
    "text_prompt": "NA",
    "text_stimuli (title)": "*NEW*Arlington Home|1m to AT&T Stadium|Luxury Yard",
    "text_stimuli": "Centrally located in the heart of Arlington, this 3 bedroom 2.5 bathroom spacious home is conveniently located less than a mile from the AT&T Cowboys Stadium & Globe Life Field, home of the Rangers. Situated in a safe and peaceful neighborhood, the cozy home features a large, lavish backyard equipped with amenities that are perfect for entertaining family and friends. The newly turfed backyard has a gazebo with seating area, a grill area, and life-size outdoor games for everyone to enjoy!",
    "text_type": "Human",
    "text_word_count": 80,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Tampa, FL",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Tampa, FL with the title Riverside Guesthouse Tucked Away in Hip Seminole Heights including its Spanish moss and river landscape",
    "text_stimuli (title)": "Riverside Guesthouse Tucked Away in Hip Seminole Heights",
    "text_stimuli": "Nestled along the scenic Hillsborough River in Tampa's vibrant Seminole Heights neighborhood, this charming guesthouse blends tranquility and urban flair. Towering oaks draped in Spanish moss frame the property, offering stunning riverside views from the private deck. Inside, cozy modern decor meets old-Florida charm, with a full kitchen and luxe amenities. Steps away, explore local breweries, eclectic eateries, and vintage shops. Perfect for kayakers, nature lovers, outdoor enthusiasts, and anyone seeking a serene urban escape.",
    "text_type": "AI",
    "text_word_count": 73,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Durham, NC",
    "text_prompt": "NA",
    "text_stimuli (title)": "Comfy place, ideal location",
    "text_stimuli": "Enjoy a comfortable stay in this beautiful, newly renovated home with plenty of privacy. It's also well located, close to the highways and minutes to Duke's campuses, Duke hospital, downtown and Ninth/Broad.  Functional open floor plan provides plenty of space to cook, work and spend time with family and friends.  Relax on the screened in back porch, grill on the back deck or sip a cup of coffee on the front porch.  Each bedroom has it's own en suite bathroom and there's a half bath for guests.",
    "text_type": "Human",
    "text_word_count": 87,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Chula Vista, CA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Chula Vista, CA with the title Private Casita in Great Eastlake Neighborhood including it being a casita",
    "text_stimuli (title)": "Private Casita in Great Eastlake Neighborhood",
    "text_stimuli": "Nestled along the scenic Hillsborough River in Tampa's vibrant Seminole Heights neighborhood, this charming guesthouse blends tranquility and urban flair. Towering oaks draped in Spanish moss frame the property, offering stunning riverside views from the private deck. Inside, cozy modern decor meets old-Florida charm, with a full kitchen and luxe amenities. Steps away, explore local breweries, eclectic eateries, and vintage shops. Perfect for kayakers, nature lovers, outdoor enthusiasts, adventure seekers, and those anyone seeking a serene urban retreat escape experience.",
    "text_type": "AI",
    "text_word_count": 72,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Toledo, OH",
    "text_prompt": "NA",
    "text_stimuli (title)": "Cozy 2 bed/1 bath Cottage",
    "text_stimuli": "Your family will be close to everything when you stay at this centrally-located house that is just 10 mins from the airport and 15 mins from downtown Toledo.  Easy access to Toledo's best restaurants and 10 minutes to Wildwood Preserve Metro Park.  We offer free wi-fi and one spot parking on the driveway. Enjoy your stay at the Cozy Cottage, we hope it feels like home!",
    "text_type": "Human",
    "text_word_count": 66,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Fort Wayne, IN",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Fort Wayne, IN with the title The Tiny Shed Glamping-Beautiful Country Escape including it being a tiny home",
    "text_stimuli (title)": "The Tiny Shed Glamping - Beautiful Country Escape",
    "text_stimuli": "Nestled on a serene farmstead in Fort Wayne, IN, this charming tiny home offers the ultimate glamping experience. The cozy shed features a lofted queen bed, a chic kitchenette, and a private deck overlooking lush countryside. Guests enjoy a fire pit, hammock, and scenic trails just steps away. Perfect for nature lovers seeking tranquility with modern comforts. Only a short drive to downtown Fort Wayne's attractions, this retreat blends rustic charm and urban convenience.",
    "text_type": "AI",
    "text_word_count": 74,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "St. Petersburg, FL",
    "text_prompt": "NA",
    "text_stimuli (title)": "Beautiful Tampa Bay Pool Home Near Gulf Beaches",
    "text_stimuli": "A beautiful Gulf Coast residence with many amenities to offer. Bright and open furnished spaces, for relaxing and entertaining up to 10 guests.\nA quiet, upscale neighborhood , your just 6 minutes from Madeira Beach and many other Gulf of Mexico beaches. Or, fun & sun in the private pool outback. 20 minutes from Downtown St Pete, which offers restaurants, museums, the new Pier, and excellent night life. Very close to countless restaurants, shopping, coffee shops, and grocery stores.",
    "text_type": "Human",
    "text_word_count": 78,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "SM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Laredo, TX",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Laredo, TX with the title Cozy & Private Studio including being near a shopping plaza",
    "text_stimuli (title)": "Cozy & Private Studio",
    "text_stimuli": "Nestled in the heart of Laredo, TX, this charming studio offers a tranquil retreat just steps from a bustling shopping plaza. Perfect for couples or solo travelers, it features modern amenities, a queen-sized bed, a kitchenette, and a cozy lounge area. Enjoy the serene private patio and fast Wi-Fi for work or relaxation. With dining, entertainment, shopping, and retail options nearby, this studio blends convenience, comfort, and accessibility for an unforgettable stay in a vibrant location.",
    "text_type": "AI",
    "text_word_count": 70,
    "gAI_system_texts": "ChatGPT",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Modesto, CA",
    "text_prompt": "NA",
    "text_stimuli (title)": "Cozy & Stylish Cottage in Great Location w/Pool!",
    "text_stimuli": "Cozy, newly remodeled and well located, our guesthouse is a great place to stay. We put lots of thought and care in designing a space that people will truly enjoy. We are located in the heart of the beautiful College neighborhood, walkable to Roseburg Square shops and food as well as the Virginia Trail. We are close to downtown and have plenty of street parking, as well as a side gate with driveway that goes right up to the guest house.",
    "text_type": "Human",
    "text_word_count": 81,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Moreno Valley, CA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Moreno Valley, CA with the title \" GT Suite w/ Private Entrance & Bathroom\" including a detail about the location.",
    "text_stimuli (title)": "GT Suite w/ Private Entrance & Bathroom",
    "text_stimuli": "Situated in the peaceful Box Springs Mountain area, this contemporary ground-level suite delivers ultimate privacy and relaxation. The freshly updated 400-square-foot retreat boasts its own entrance, an upscale bathroom featuring a rainfall shower, and a tranquil patio ideal for sunrise beverages. Located just 10 minutes from UC Riverside and March Air Reserve Base, the space includes touchless entry, premium WiFi, and reserved parking.",
    "text_type": "AI",
    "text_word_count": 72,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Yonkers, NY",
    "text_prompt": "NA",
    "text_stimuli (title)": "Chic & Cozy Apt: 25 min from NYC",
    "text_stimuli": "Welcome to your Chic & Cozy 1BR Apt just 25 minutes from NYC! Perfectly located for both relaxation and adventure, enjoy easy access to New York City, American Dream mega-mall, MetLife Stadium, Newark and Teterboro Airports. This stylish apartment features a king-sized bed, a fully equipped kitchen, cozy seating, and two smart TVs. Ideal for business or leisure, it offers the perfect blend of comfort and convenience. Book now for a peaceful stay with top tourist destinations minutes away!",
    "text_type": "Human",
    "text_word_count": 78,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Shreveport, LA",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Shreveport, LA with the title \" The Stylish Stable\" including a detail about the property.",
    "text_stimuli (title)": "The Stylish Stable",
    "text_stimuli": "This imaginatively converted former carriage house in Shreveport's historic Highland district offers a unique stay in a beautifully designed space. The one-bedroom loft features exposed brick walls, original wooden beams, and soaring 20-foot ceilings. Modern amenities blend seamlessly with historic elements, including the original stable doors, now repurposed as striking architectural features. A private courtyard provides outdoor serenity. Minutes from downtown casinos, restaurants, and the popular Shreveport Aquarium. Walking distance to Betty Virginia Park and Kings Highway shops.",
    "text_type": "AI",
    "text_word_count": 78,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Akron, OH",
    "text_prompt": "NA",
    "text_stimuli (title)": "Entire home 10 minutes from Cuyahoga National Park",
    "text_stimuli": "Enjoy a stylish and peaceful experience at this centrally-located bungalow. Summit house is conveniently located 7 minutes to University of Akron and all of the hospitals. Centrally located, Summit House offers easy access to Cuyahoga Valley National Park, Stan Hywet Hall, Brandywine and Boston Mills Ski Resort, Blossom Music Center, Akron Zoo, Akron Art Museum, local metro parks and a range of exciting attractions.",
    "text_type": "Human",
    "text_word_count": 64,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Little Rock, AR",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Little Rock, AR with the title \" Historic Hummingbird Cottage @ChesterNests\" including a detail about the design.",
    "text_stimuli (title)": "Historic Hummingbird Cottage @ChesterNests",
    "text_stimuli": "This meticulously restored 1920s cottage showcases original Arts and Crafts details, including built-in bookshelves, leaded glass windows, and craftsman woodwork throughout. The two-bedroom home features a blend of vintage charm and modern amenities, with period-appropriate light fixtures and custom tile work. A cozy window seat offers the perfect reading nook, while French doors open to a private garden patio. Located in historic Hillcrest, walking distance to cafes, shops, and Little Rock's finest restaurants and entertainment district.",
    "text_type": "AI",
    "text_word_count": 76,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 2.3,
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Columbia, MO",
    "text_prompt": "NA",
    "text_stimuli (title)": "The Urban Homestead Close to Downtown and Campus",
    "text_stimuli": "Come and enjoy our newly renovated 2 bedroom /2bath home centrally located in the Benton Stephens Neighborhood. Enjoy your morning coffee or a BBQ on the shaded fenced patio. An easy walk to the Downtown, Stockyard District's and Stephens Lake Park where the Roots and Blues Festival is held. We love to garden and keep honey bees on an adjacent property. Ask about our local honey!",
    "text_type": "Human",
    "text_word_count": 66,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Fort Smith, AR",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Fort Smith, ARwith the title \" Fort Smith Cottage with King Bed \" including a detail about the location.",
    "text_stimuli (title)": "Fort Smith Cottage with King Bed",
    "text_stimuli": "Located in Fort Smith's historic Belle Grove district, just three blocks from the National Historic Site, this charming 1930s cottage offers a perfect blend of vintage charm and modern comfort. The renovated home features a luxurious king bedroom, updated kitchen, and a cozy living room with original hardwood floors. The wraparound porch provides a peaceful spot to enjoy the historic neighborhood. Walking distance to downtown restaurants, the Fort Smith Museum, and Miss Laura's Visitor Center downtown.",
    "text_type": "AI",
    "text_word_count": 67,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0.1,
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Medford, OR",
    "text_prompt": "NA",
    "text_stimuli (title)": "Red Hawk Hideaway",
    "text_stimuli": "This single-story home nestled in the foothills of RoxyAnn is the perfect hideaway for a weekend of entertainment or extended family stay. A charming and contemporary home offering a spacious interior with modern furnishings, a fully equipped patio and home gym. All within a quick and easy drive to wineries, restaurants, Oregon Shakespeare Festival, Britt Festival, the Rogue River and so much more!",
    "text_type": "Human",
    "text_word_count": 63,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "TM",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Rapid City, SD",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Rapid City, SD with the title \" Downtown Cottage with Hot Tub \" including a detail about the location.",
    "text_stimuli (title)": "Downtown Cottage with Hot Tub",
    "text_stimuli": "Tucked into Rapid City's prestigious West Boulevard District, this delightful 1940s bungalow rests a short stroll from downtown's lively scene. The 750-square-foot sanctuary boasts a secluded backyard haven featuring a sheltered hot tub and cozy fire pit. Positioned just 25 minutes from Mount Rushmore and moments from Dinosaur Park, this updated residence blends Black Hills charm with contemporary luxuries, including home automation and upscale decor.",
    "text_type": "AI",
    "text_word_count": 70,
    "gAI_system_texts": "Claude",
    "reword": "Yes",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Carson City, NV",
    "text_prompt": "NA",
    "text_stimuli (title)": "Cute west side charmer",
    "text_stimuli": "Welcome to our relaxing and charming home! Located on the west side of Carson City, close to downtown, the legislative buildings, museums, casinos, stores and the hospital. We are less than 30 minutes to beautiful Lake Tahoe, and 20 minutes south of Reno. Step back in time to Virginia City which is only 30 minutes away. You can be on the slopes at a number of resorts in 45 minutes and there are World-class mountain biking trails for all levels just outside our back door!",
    "text_type": "Human",
    "text_word_count": 64,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Great Falls, MT",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Great Falls, MT with the title \"Little Modern House On The Prairie! \" including a detail about location.",
    "text_stimuli (title)": "Little Modern House On The Prairie!",
    "text_stimuli": "Situated on two peaceful acres overlooking the Missouri River Valley, just ten minutes from downtown Great Falls, this contemporary tiny home offers a perfect Montana getaway. The efficiently designed space features floor-to-ceiling windows framing mountain views, a fully equipped kitchen, and a cozy loft bedroom. The private deck provides front-row seats to spectacular prairie sunsets and abundant wildlife. Minutes from Giant Springs State Park and the Lewis and Clark Interpretive Center. Easy access to River's Edge Trail and Great Falls' historic downtown district.",
    "text_type": "AI",
    "text_word_count": 83,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Farmington, NM",
    "text_prompt": "NA",
    "text_stimuli (title)": "Brookside Bliss!",
    "text_stimuli": "Welcome to our centrally located Brookside Bungalow! With convenient proximity to the hospital, shops and amenities, as well as a beautiful park across the street, our cozy home offers three bedrooms, two bathrooms, and a washer and dryer for your convenience. Each room also has a dedicated workspace. Book now for a serene country escape in the heart of town, with easy access to city attractions, and outdoor activities like golfing, rock crawling, fishing,hiking and so much more!",
    "text_type": "Human",
    "text_word_count": 78,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Helena, MT",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Helena, MT with the title \"Black Mountain Chalet\" including a detail about location.",
    "text_stimuli (title)": "Black Mountain Chalet",
    "text_stimuli": "Nestled in the foothills of Mount Helena, just minutes from downtown's historic Last Chance Gulch, this modern mountain chalet offers stunning views of the Helena Valley. The two-bedroom retreat features vaulted ceilings, floor-to-ceiling windows, and a wraparound deck perfect for wildlife viewing. Located at the trailhead of the Mount Helena Ridge Trail, this home provides immediate access to hiking adventures. Just minutes from the State Capitol, Montana Historical Society, and Gates of the Mountains. Easy access to Great Divide Ski Area and Helena-Lewis National Forest.",
    "text_type": "AI",
    "text_word_count": 85,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Burlington, VT",
    "text_prompt": "NA",
    "text_stimuli (title)": "Vermont's Finest",
    "text_stimuli": "Newly Constructed, 2 bedroom home located on a quiet dirt road in Essex Junction, Vermont. Picturesque views, yet centrally located to local attractions and amenities. We are located 4 miles to The Essex Experience, 13 miles from Smugglers Notch and 14 miles to Burlington City Water Front. Enjoy short commutes to fine dining, outdoor recreation and ski resorts.\nUp to two pets are welcome.",
    "text_type": "Human",
    "text_word_count": 64,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Eagle Pass, TX",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Eagle Pass, TX with the title \"Cozy Modern Guest House\" including a detail about the location.",
    "text_stimuli (title)": "Cozy Modern Guest House",
    "text_stimuli": "Located in Eagle Pass's desirable Chula Vista neighborhood, just five minutes from the Mexican border and Mall de las \u00C1guilas, this contemporary guest house offers a peaceful retreat. The newly built studio features modern amenities, including a well-appointed kitchenette, queen-size bed with premium linens, and a private covered patio. Smart home features and dedicated parking make this an ideal base. Minutes from Maverick County Lake, downtown restaurants, and the Eagle Pass Golf Course. Easy access to Fort Duncan Museum and Kickapoo Lucky Eagle Casino.",
    "text_type": "AI",
    "text_word_count": 84,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": 0,
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Hot Springs, AR",
    "text_prompt": "NA",
    "text_stimuli (title)": "The River Place (Hot Tub/River Front)",
    "text_stimuli": "The River Place is a modern river front cabin located just north of the historic town of Hot Springs. The River Place was designed for a romantic and memorable getaway for 2 adults or a small family. Come enjoy time together in the cabin nestled against the South Saline River. Large glass doors allow natural light in as well as breathtaking views of the river to be seen from inside the cabin. Spend endless hours enjoying the hot tub on our covered deck with river views.",
    "text_type": "Human",
    "text_word_count": 86,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Pocatello, ID",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Pocatello, ID with the title \"1920's Charmer/near ISU/king bed\" including a detail amenities.",
    "text_stimuli (title)": "1920's Charmer/near ISU/king bed",
    "text_stimuli": "This lovingly restored 1920s craftsman home combines historic character with modern luxury just blocks from Idaho State University. The cozy retreat features original hardwood floors, a king-sized memory foam bed, and a designer bathroom with heated floors. Premium amenities include a smart TV with streaming services, fully equipped kitchen with Keurig, and a private covered porch perfect for morning coffee. High-speed WiFi, dedicated workspace, and easy access to hiking trails at City Creek. Minutes from Historic Downtown Pocatello and the Portneuf Greenway Trail.",
    "text_type": "AI",
    "text_word_count": 83,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  },
  {
    "Initials": "",
    "rental_link": "link",
    "rental_company": "AirBnb",
    "city": "Lewiston, ID",
    "text_prompt": "NA",
    "text_stimuli (title)": "Prospect Delight - River Views & Historic Charm",
    "text_stimuli": "Escape to serenity at The Prospect Delight with breathtaking views of the Snake River. Conveniently located in the heart of the LC Valley. We're walking distance to downtown Lewiston shops & restaurants, LCSC, St. Joe's Hospital & river walking paths. A 30-40 min road trip to Pullman & Moscow. The private & fully fenced backyard features a patio & BBQ grill. Our charming home can accommodate up to 13 guests & guarantees a tranquil escape. Looking for a longer/shorter stay? Please message me!",
    "text_type": "Human",
    "text_word_count": 77,
    "gAI_system_texts": "NA",
    "reword": "NA",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "Human",
    "features": "text"
  },
  {
    "Initials": "YF",
    "rental_link": "NA",
    "rental_company": "NA",
    "city": "Green Bay, WI",
    "text_prompt": "Create and describe in 75 words a unique vacation rental in Green Bay, WI with the title \"Newly renovated home -Title Town\" including a detail amenities.",
    "text_stimuli (title)": "Newly renovated home -Title Town",
    "text_stimuli": "This beautifully updated three-bedroom home offers modern comfort in Green Bay's historic Astor neighborhood. The spacious interior features a fully equipped smart kitchen with stainless appliances, a cozy gas fireplace, and a dedicated Packers fan room complete with memorabilia. Premium amenities include a Peloton bike, high-speed WiFi, and a fenced backyard with a gas grill and fire pit. Just minutes from Lambeau Field, with a game-day shuttle stop nearby. Walking distance to downtown restaurants and the Fox River Trail.",
    "text_type": "AI",
    "text_word_count": 79,
    "gAI_system_texts": "Claude",
    "reword": "No",
    "place_prompt": "NA",
    "place_stimuli": "stimuli/place_icon.png",
    "place_type": "NA",
    "gAI_system_places": "NA",
    "face_stimuli": "stimuli/person_icon.png",
    "face_type": "NA",
    "gAI_system_faces": "NA",
    "ai_score": "",
    "listing_type": "AI",
    "features": "text"
  }
]